### PR TITLE
Tweaked presentation of slots messages

### PR DESCRIPTION
**Pull request by Kanuan**
- DS4Windows will only consider slots valid if they are Slots 1 up to 16
    - Any value outside of this range is probably outside of the usual windows Xinput range, meaning vigembus reported back "256", or because an old version of vigembus failed to inform the actual slot
    - Slots outside of this range will appear as "?"
- Made virtual xbox 360 plug-in messages display the current xinput slot
- Tweaked some log messages
    - tried to make it clearer when DS4Windows means its output slots and not xinput slots
    - tried to make it clearer when DS4Windows means virtual controllers
    - made the "found controller X" log occur everytime a new controller is found and not only on app startup
    - Small code refactor in some places to simplify code and remove redundant code blocks

image

image

### CODE REVIEW

**Comment by Kanuan** [comment]
Sorry for closing/opening/closing the last PR. I've made a mess.

Now everything seems to be in order.

I had to alter the XInputSlotNum property to only accept values between 0-15, because even if the vigembus report back an actual value, if it's outside of the usual XInput Slots range (1-4) it will be 256, which basically means invalid

**Comment by Yohoki** [comment]
Really like the addition of the 'virtual' keyword in the logs. Makes it a lot clearer. Might I recommend replacing 'input controller' with 'physical controller', to match the new wording?

**Comment by Kanuan** [comment]
> Might I recommend replacing 'input controller' with 'physical controller', to match the new wording?

I've considered the possibility of ds4windows accepting inputs controllers from the network or something like, but, yeah, probably should go with "physical" for the time being. Will update it when I have the time

**Comment by Ryochan7** [comment]
Ended up reducing the max xinput slot number to 8. Other than that, there were some good changes.

**Pull request merged**
