### PR TITLE
Fixes vibration bugs when more than one gamepad is connected

### LINKED ISSUE #2604: Vibration bugs when two DualSence gamepads connected
DS4Windows 3.1.6, latest HidHide and ViGemBus drivers.
When two dualsense controllers are connected and both are emulated as dualshock 4 (all the settings are set to passthru), in the game - playing a vibration on one controller causes the same vibration on the other, and vice versa. And almost immediately a problem of constant vibration on one of the controllers appears. 
Tested in It Takes Two (Origin).

Passthru light is also works strange, it is black or incorrect color. In most cases it works correct after DS4Windows restart when the gameplay of the game already started.

### PR DESCRIPTION
**Pull request by nefarius**
Fixes #2604

I've merged your modifications to the SDK upstream so you can directly consume the SDK NuGet, it's feature-equivalent with the patched DLL in the repository.

This SDK version has the proper separation of output reports per emulated device implemented and tested, the API surface and behavior has not changed. For details, please see the referenced issue.

Cheers

### CODE REVIEW

**Comment by nefarius** [comment]
Wanna look into this as well before merge https://github.com/ViGEm/ViGEmClient/issues/22#issuecomment-1279828311

**Comment by nefarius** [comment]
Now [this issue](https://github.com/Ryochan7/DS4Windows/issues/2604#issuecomment-1279910148) has been ironed out as well.

**Comment by Ryochan7** [comment]
Thank you for looking into this. Tested in HTML5 Gamepad Tester and The Witcher 3 and it seems to do the trick. Although, I ended up reverting back to using a custom built library in commit 073b94dec8fe85c88608269707ee899662e3b8c3. Still need the notification queue in the ViGEmClient code to prevent unintentional sustained rumble in some cases; encountered sustained rumble fairly quickly in the ParaLLEl N64 RetroArch core while play Ocarina of Time with the latest vanilla library. Also wanted to keep some of the build optimizations used. Got the custom repo merged with the upstream ViGEmClient code so the latest custom built libraries are using the fixes.

**Comment by nefarius** [comment]
If I add the same mechanism for the virtual x360 we can completely toss the notification code, right?

**Pull request merged**
