### PR TITLE
Improvement 1: Pre-defined output curves using a pre-fixed calculation logic. Now only Custom curve uses bezier logic.  Improvent 2: Steering wheel emul mode using vjoy output axis support in UseDInputOnly mode.

### PR DESCRIPTION
**Pull request by mika-n**
Pre-defined output curves initialized using a pre-fixed formula. Now only the "Custom" output curve goes through bezier curve logic, but at runtime all output curve options are mapped using a lookup table (better performance and easier code maintenance).

### CODE REVIEW

**Comment by mika-n** [comment]
@Ryochan7  This pull request is sort of fusion of the old curve output logic and the new bezier curve output logic. Option 1..5 (0=linear) are initialized using the the same old calculation logic, but the output result is "calculated" using a lookup table access at runtime (performance). Only the curve output "Custom" is now customizable bezier curve output.

The code to initialize those existing pre-defined curves is part of BezierCurve.js code module, but the calculation logic there is the same as in the old Mapping.cs routines. However, it is much easier to maintain these calculations in this BezierCurve.js code module and rutime mapping performance is better because the output table is pre-calculated.

**Comment by mika-n** [comment]
Added also support for "steering wheel emulation mode" in UseDInputOnly mode if the output axis of steering wheel emulation is VJoy device and not an axis of xbox360/dualshock4 device. This way if a profile uses just mouse, keyboard and steering wheel emulation with VJoy axis re-mapping rules then it works without virtual gamepad device (UseDInputOnly=true) and in that case there is no need to use exclusive mode or HidGuardian either.

**Comment by Ryochan7** [comment]
Still noticed a difference so the old routines were added back in after merging the changes.

**Comment by mika-n** [comment]
> Still noticed a difference so the old routines were added back in after merging the changes.

@Ryochan7   Hmmm... There is one very slight difference between the original and "new" code on those old curves. The difference is on the "left side" of the LS/RS axies where input value 128 is sort of center point. The "right side" of the 128 center point in LS/RS is identical between the original routines and the new routines in BezierCurve.js code module (ie. those curve specific initialization routines and not the true bezier custom curve).

Here is an online spreadsheet file illustrating how axis INPUT (0..255) value is mapped using the original routines and the new curve routines in BezierCurve.js code module.
https://ethercalc.org/vw21a00iasp9

INPUT column is the raw input axis value
xxx_orig = Output value using the original routines
xxx_new = Output value using the methods in in BezierCurve.js module

As you can see the "right hand side" from 128 center point is identical, but left hand side has slight difference. However, I think the original logic was a bit wrong because it hits the "zero bottom value" too early and this way looses slightly precision. This is not that obvious in EnchPrec/Quad/Cubic curves, but EaseOut_Quad shows it more clearly. See how the 4_EaseOutQuad_orig column hits zero output value too early compared to its "right hand side" counterpart having 255 output value.

Anyway. If the difference is seen then I would still recommend to get rid of the original IF-THEN-ELSE code logic and using just the lookup table result table in all output curve modes. It gives performance benefits and the calculation logic for these curves is maintained in one place (BezierCurve.js code module) instead of repeated copy-paste code.

I can change those Init_xxxx curve specific initialization routines in BezierCurve.js to re-use the original "potentially wrong" left-hand-side mapping result, so the net result would be 
- exactly identical output value table compared to the original routines
- benefiting from "one place to code maintenance per curve" instead of copy-pasted code per axis
- better runtime performance through lookup result table. 

I think this would be the best solution if you want to keep identical output curve values also in the "left hand side" of the center 128  input point in LS/RS axis. What do you think?

**Pull request merged**
