### PR TITLE
Fixup the guesswork sixaxis implementation with a correct one

### PR DESCRIPTION
**Pull request by rajkosto**
You will have to revise how you handle the "gryodirs" handling as well as the mouse gyro (for which i suggest not using the gyro, but low-pass filtered accelerometer, and then use this https://stackoverflow.com/questions/3755059/3d-accelerometer-calculate-the-orientation with X = -sonyZ Y = sonyX Z = -sonyY), now that you have the correct inputs.

I suggest that people who want to work on motion control stuff read the attached materials in this post: https://www.researchgate.net/post/Does_anyone_have_a_6-DOF_IMU_Kalman_Filter and/or watch this video: https://www.youtube.com/watch?v=C7JQ7Rpwn2k
This will help you understand what values the sensors actually give you (no, a gyro does not give you absolute orientation, and accelerometers will always have the gravity vector subtracted so you cannot use them raw for linear motion)

Whatever you do, DO NOT change the SCALE, SIGN, or ORDER of the gyro or accelerometer properties exposed in DS4State/computed in DS4Sixaxis class, because they are currently setup to match the Sony convention (https://images.sshnuke.net/2017-07-07_04-02-47.png) as well as my ScpToolkit fork (which is the first one I actually fixed all this stuff on, for both DS3 and DS4, and it can be found here: https://github.com/rajkosto/ScpToolkit/commits/master)

### CODE REVIEW

**Comment by Ryochan7** [comment]
There are some good ideas with this change but it does not work for any gyro nor accelerometer functionality. Gyro mouse does not work due to the calculations being performed which leaves the final output in the assigned dead zone under almost any movement. Sixaxis controls no longer respect the assigned dead zones and will activate with the slightest rotation. The controls being activated are also inconsistent. The Controller Readings tab in the Options form is completely broken. One other problem is that the application runs very slowly with the change and XInput emulation is almost unusable due to added lag.

I had only gotten the current code that interprets data from the IMU to the point that it would fix some initial bad assumptions and use the data to try to make Gyro mouse mode usable. Unfortunately, I left a lot of bad conventions in the code to not have to edit other parts of the program such as the Controller Readings tab in the Options form. Getting the Gyro mouse routine to work well enough was all that I wanted.

There is a lot more work that could have been done and some of your changes would be a welcome addition. As it is, the code needs some work before it can be merged. For some examples of current profiles that use gyro functionality, here are a couple of profiles that utilize Gyro mouse that I have used.

https://www.dropbox.com/s/kz90kr3n207ec4u/gyro%20test.xml?dl=0

https://www.dropbox.com/s/7vcr9zfpykljgec/Turok.xml?dl=0

**Comment by rajkosto** [comment]
I don't really care about the gyro functionality inside DS4Windows, I only need it correct so that the udp server i added can expose it to external applications: https://puu.sh/wDE0T/356b1d7953.mp4

**Comment by rajkosto** [comment]
These two new commits should address all 3 of your concerns
However, in the future, it would be best to work with correct sensor readings instead of mangled ones.

**Comment by Ryochan7** [comment]
There are a good amount of examples of how Gyro mouse can be used. Some examples would be Mouse Look mode with the Razer Hydra (it uses a magnetometer but the idea is the same), Gyro mouse mode with the Steam Controller, and even Gyro mouse mode using the PS4 controller support built into Steam. Here are two quick examples showing motion controls being used to operate a virtual mouse for playing PC games.

https://www.youtube.com/watch?v=gR2GR0X8fqQ - Motion Controlled: DOOM with the Razer Hydra

https://www.youtube.com/watch?v=qTIHqkHvKII - Turok Remastered + Steam Controller | Playtest & Impressions 

Having some functionality in DS4Windows that slightly operates like the Gyro mouse mode available in Steam was the goal with the current Gyro mouse implementation. Personally, I now prefer the Gyro mouse mode in DS4Windows over the implementation in Steam but the DS4Windows version does not offer all the options the Steam version does. I have only beaten Turok using Gyro mouse for aiming but at least the current Gyro mouse functionality in DS4Windows has shown to be a usable alternative to using the right analog stick for camera control.

Smoothing for Gyro mouse mode is done on output mouse movement and not input gyro data. The main reason for a smoothing option is to remove some jitter that can naturally occur from the movement of your hands. One smaller reason is because Steam offers smoothing for Gyro mouse although the version of smoothing offered by Steam impacts the controls too much for my liking. I think that enabling smoothing offers a slightly better experience than using the raw data from the IMU but the mouse functionality works fine without enabling smoothing.

At this point, I would rather keep the mangled but mostly working code than what you are trying to concoct. You not only broke gyro functionality but the entire application in the process and you apparently cannot be bothered to properly test your changes. Your most recent update only improves XInput emulation slightly but it is still worse than DS4Windows version 1.4.52 and every other option out there for using a DS4 on Windows. The fact that you decided to remove some of my recent changes with old code that did not work in the first place doesn't help either. Your changes would be a far greater liability than an asset. This issue is closed.

**Pull request closed without merging**
