### PR TITLE
Fixup the guesswork sixaxis implementation with a correct one - take 2

### PR DESCRIPTION
**Pull request by rajkosto**
Doesn't break anything this time (gyro mouse works the same as far as I see, slightly more accurate because using floats, which is what you should always use as inputs to atan2 anyway). 
But it does label the properties you use in Mapping.cs with a "fake" prefix (they have to be fake, as you are modifying them from the wrong place), which might anger you :P

Merge or don't (ignore my commit names, just look at the overall changes), I don't care, just trying to make maintaining my fork easier.

### CODE REVIEW

**Comment by Ryochan7** [comment]
> I'm sure **you** can fixup all the cases where gyro is already used inside DS4Windows just by applying proper scale factors (at least now you know it's in deg/s !

This is pretty much where communication initially broke down. That is not how pull requests work. It is not my job to fix the problems that you create. Some of the questions that you raised made me concerned that you were not informed enough in the problem that you were claiming to have solved. Eventually, I discarded your ideas in general and decided that the program would be better off without the change.

This time around, there are fewer problems with the fork but the main complaints still apply. XInput emulation suffers significantly with the change. With the unnecessary scaling being done for Gyro mouse and the time delta not being used as expected, Gyro mouse is much worse off; (us / 200) will not give the same result as (s * 200). Using the raw input from the device is better for that routine than throttling input the way that is being done now (raw vs (raw/16)); converting back to raw input would be easy enough but two extra calculations each poll and precision are some concerns. I personally would have stuck with storing both scaled and raw fields in the SixAxis class.

There are also a lot of questionable coding practices that you have used that I personally do not like and some that can lead to extra input lag when used in the controller input threads. One obvious coding practice is the reliance on using properties even inside the class that has direct access to the underlying field; DS4SixAxis is a big culprit. Besides, based on my own experience, using properties for access outside of a class is much slower than using explicit getters so explicit getters are implemented for use with code run in input threads; using properties has not been a concern for the main GUI thread.

At this point, the code is still not ready to be included.

**Comment by rajkosto** [comment]
"I'm sure you can fixup all the cases where gyro is already used inside DS4Windows just by applying proper scale factors (at least now you know it's in deg/s !" was reverted with the 2nd commit in the first pull request, because trying to bring sanity to Mapping.cs would be a fool's errand, so it can keep using the "fake" values all it wants.

I get the same speed on my mouse gyro as it was before my change, you can use /16 and scale the time differently if you want, and also are you running it in Debug mode for Properties to be slower than raw values ? I don't understand why this would matter at all. Nobody using my fork has complained about anything being slower ?

**Comment by Ryochan7** [comment]
I had even given your 1.4.84 build a try to make sure what I was experiencing was not a fluke. Your build exhibits the same performance problems when compared to vanilla 1.4.84. The timestamp calculation differences should give an idea about what is technically correct and what the .NET Runtime will run reasonably. Another prime example is the following small commit. You would not believe how big of a difference switching around one if statement made.

https://github.com/Ryochan7/DS4Windows/commit/39930cf2e8ea5a58e403ffec977a976fefa979f3

A lot of time on this project is spent just trying to get .NET to play nice when adding new features. Some coding practices that I normally wouldn't do (temporary class fields) are being done for improved application performance.

The idea of storing the elapsed time in DS4State was to possibly use it for mouse stick calculations as opposed to the time obtained from a Stopwatch in DS4Device. It would probably be better to get the time delta from DS4State as opposed to having to get a reference to the DS4Device object to get access to the relevant field. It might be used for touchpad mouse in the future as well. As I see it, the time delta will likely be used in multiple routines so calculating the time delta in advance is better than having to calculate the time delta in several sections of code. So far there has been no need to have access to the full timestamp by any routines so only the time delta is available for access.

Gyro mouse is different and examining the code shows that. The routine that you are using actually results in faster mouse speed than the routine in DS4Windows now.

No matter what, the end result are what matters most. XInput performance is the biggest issue. Maybe other people think it is acceptable. When I picked up this project, I was fine with the performance of DS4Windows version 1.4.53 and I had even stated before that it was the best option available at the time even compared to the DS4 support built into Steam. Changing the program and finding ways to improve XInput performance has made it so I would not want to go back to that kind of performance. Having an extra feature included is not worth the cost if it compromises application performance.

This whole discussion should have just been filed as a normal issue from the start as opposed to a pull request.

**Comment by rajkosto** [comment]
If the JIT is so finnicky, then maybe it's worth exploring migrating this to an AOT compiled platform like .net core 2.0 (which now switched to RyuJIT for x86 even when not AOT compiled), and just bundling the entire runtime ?

**Comment by Ryochan7** [comment]
I tried to work on this with version 1.4.92 and it didn't work out too well. Progress halted once the calibration report difference had to be taken into account. Some nuclear options had to be done to make some progress. Just for reference, here is a Gist with the incomplete patch for that version. This will be worth trying again sometime.

https://gist.github.com/Ryochan7/cfe1e28e1586e3d0989ef6db2f996acc

**Comment by Ryochan7** [comment]
Version 1.4.97 now has a calibration routine for the IMU. It seems to work fairly well when using Gyro Mouse and XInput performance has not been impacted by the change.

**Pull request closed without merging**
