### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ahmed3457**
it requires windows 7 or greater as long as it's fully updated,
it ran well on my current machine

### CODE REVIEW

**Comment by Ahmed3457** [comment]
https://user-images.githubusercontent.com/93637332/204641542-823c9d8b-fa5b-448a-b5b2-c0db896f6bc8.mp4

**Comment by Kanuan** [comment]
Some new features of ds4windows require the latest version of the ViGEmBus, which can only be installed on Windows 10.

The last Win7 compatible version of vigembus is 1.16.something.

Because not all features are compatible with Win7, and support for it might be fully removed from ds4w at any given moment if necessary, Ryo changed the minimum system requirement from Win7 to Win 10 a long time ago

**Comment by Ryochan7** [comment]
The requirements have been more based on decisions made by Microsoft and recent versions of ViGEmBus only supporting Windows 10 and later. I have been trying to still support Windows 8.1 until the EOL date hits in January 2023.

I cannot remember when I did it but I removed a few DS4 Bluetooth workarounds that were only needed in the code due to Windows 7. Current versions of DS4Windows do not support a DS4 connected to Bluetooth when run on Windows 7. Another thing is that DualSense force feedback support on BT does not work on Windows 7; I cannot remember why but that is also the case when using Steam Input.

**Comment by Ahmed3457** [comment]
This means windows 7 is not fully supported

**Comment by Ahmed3457** [comment]
and Some features may not work
 but this still mean it's not fully unsupported

**Pull request closed without merging**
