### PR TITLE
Nacon Revolution Unlimited Pro and Hori Fighting Commander gamepad support. 

### PR DESCRIPTION
**Pull request by mika-n**
Added Nacon Revolution Unlimited Pro and Hori Fighting Commander gamepad support. 
Also fixed index out of bounds error in hidlibrary.readSerial function in case serial# reading failed (uses dummy zero MAC address in readSerial failed). The dummy zero MAC address also makes it possible to use those gamepads in DS4Windows because the result string is not empty (later on in DS4Windows code path there is a check for IsNullOrEmpty mac string and if the string is empty then DS4Windows won't use the gamepad at all).

### CODE REVIEW

**Comment by mika-n** [comment]
@Ryochan7  This commit contains support for two new DS4 compatible gamepads (except that those gamepads fail to report a MAC identifier).  The readSerial tweak is related to that case where those gamepads crash (throws an exception) in hidlibrary.readSerial method.

The commit history has handful of messages about vJoyFeeder but those commit messages can be ignored. This pull request does NOT contain any changes in vJoyFeeder support. I have a separate branch where ForceFeedback effects sent to vJoy device are re-directed and converted as rumble effects in DS4 gamepad. It is handy if 360-steerignWheel emaultion axis is vJoy and game sends FFB effects to a device mapped as steering axis in a game. That change is not yet release ready even when I already use it in EuroTruck simulator.

**Comment by mika-n** [comment]
@Ryochan7  ping. This support for two new controllers didn't quite make it to V1718/V1719 release.

**Comment by Ryochan7** [comment]
I have been spending too much time working on the WPF port lately. Version 1.7.18 was mostly filled with random fixes and tweaks found while working on the WPF version. I will pull your updates in a bit and check them out. Hopefully it won't take as long to get version 1.7.20 released.

**Comment by Ryochan7** [comment]
Thank you for the changes. I ended up adding a const for the blank serial string. I will try to get a new release out in the next few hours.

**Pull request merged**
