### PR TITLE
Support for various non-standard DS4 gamepads. Parameterized VidPidInfo structure to eliminate customized if-then-else logic per gamepad type.

### PR DESCRIPTION
**Pull request by mika-n**
@Ryochan7  This pull request has four main parts. Together these changes make it possible to support even more custom and fake DS4 gamepads which don't behave exactly the same as genuine DS4 gamepad. Usually this is an issue in BT mode.

Part 1: Support for various non-standard DS4 gamepads. DS4Windows.VidPidInfo structure has a new featureSet flag set which is used to fine tune how the specific gamepad behaves and what it supports (no need to do if-then-else all over the other code per gamepad type).
This is used especially to make it possible to use Razer Raiju TE BT and Razer Raiju UE BT gamepads because those are a bit weird DS4 gamepads in BT mode. Those behave like a combination of USB and SonyWirelessAdapter connected gamepads in BT mode (ie. 0x01 incoming data packet and 0x05 output data packet). Interesting thing is that those gamepads don't need "native DS4 mode switching" in BT mode, so those don't suffer from the dead BT device handle issue either.
This is related to #988 ticket and a solution worked out there.

Part 2: VidPidInfo.FeatureSet flags (see DS4Devices.cs) are used to optionally disable "writeData" functionality of DS4Windows app. There are some DS4 copies (fake DS4s?) which don't seem to support data outputting (ie. sending lightbar/rumble/pollFreq data to DS4). The new profile option "Enable Output data to DS4" in Other tab page can be used to disable data writing and this way make it possible to use those non-standard DS4 gamepads.
This is related to #1209 ticket.

Part 3: Some gamepads seem to send only "PC-friendly data packets" in BT mode (ie. the BT input report data doesn't have 0x11 data type) . PerformDS4Input has a logic where periodic failing crc32 and data packet type checks trigger DS4Windows to switch over to accept incoming PC-friendly data packets even in BT mode (ie. 0x01 data type).
This is related to #1193 ticket.

Part 4: Merged another pending pull request made by @stryblt to support the new VidPid.FeatureSet flag fields #1203 
 
This pull request does not change how standard DS4 gamepads (genuine and currently supported non-official) behave in BT, SWA and USB mode, but make it easier to support new "weird" gamepads in the future (and adds support to various of those "weird" gamepads).

### CODE REVIEW

**Comment by Ryochan7** [comment]
I will have to pull and check out these changes later. Using flags to denote a feature set for a controller is a good idea. The hid-sony Linux driver uses a similar approach to specify gamepad type and the capabilities of the controller. A change like this would probably be worthy of a bump to version 2.1.

Some of the comments confirm my suspicion that some of those non-standard DS4 controllers would probably act weird on an actual PS4 console.

**Comment by nosfay** [comment]
> Part 2: VidPidInfo.FeatureSet flags (see DS4Devices.cs) are used to optionally disable "writeData" functionality of DS4Windows app. There are some DS4 copies (fake DS4s?) which don't seem to support data outputting (ie. sending lightbar/rumble/pollFreq data to DS4). The new profile option "Enable Output data to DS4" in Other tab page can be used to disable data writing and this way make it possible to use those non-standard DS4 gamepads.

Does it work like "all or nothing" option ? I mean, if an original controller and a non-standard one are connected, does rumble and lightbard are disabled for all ?

**Comment by mika-n** [comment]
@nosfay  "Part 2: Optional Enable Output data for DS4" option is a profile setting, so each controller may use different profile. Therefore it is "case by case, one by one" selection.

**Comment by Ryochan7** [comment]
These changes will be put in a new release once the Changelog issue is taken care of. I am sticking with the plan to make this a definitive change for a version 2.1 update. Hopefully these changes will help more people using third party controllers. Thank you for these changes.

**Pull request merged**
