### PR TITLE
Runtime generated MAC (serial#) address in readSerial method if hardware serial# was not found.

### PR DESCRIPTION
**Pull request by mika-n**
If reading of hardware serial# (MAC) fails then readSerial function generates a runtime MAC address using devicePath value. This solves cases where UDPServer and Cemulator doesn't work with blank serials (and linkToProfile and 360SteeringWheel calibration linking to a certain gamepad).

Some non-official DS4 compatible gamepads doesn't seem to support the same way of reading the serial# from a controller as the official gamepads. In those cases hiddevice.readSerial returned always a blank serial# but it caused problems in UDPServer and Cemulator (UDPServer and Cemu reported the gamepad as being in disconnected state). Also, link-to-profile and 360-steeringWheel-calibration linking to a certain gamepad didn't work with blank serials. 

This patch uses the last parts of devicePath string to generate a dummy runtime MAC address to workaround those problems. WinOS generates the last 3 parts of devicePath string from USB hub/USB port and from BT pairing values. Those values remain the same as long the gamepad is connected to the same USB port (wired) or BT pairing remains the same (wireless). If PC has two identical controllers with the same VID/PID then the last 3 items of devicePath are different because two controllers must have been connected into two different usb ports or have different BT pairing link. For the purpose of this MAC address in DS4Windows it is enough to have runtime uniqueness even when the generated MAC is not hardware tied to a certain gamepad device.

The ideal solution would be to debug those non-official DS4 gamepads to find out why and how the physical serial# should be read from those gamepads. For now this "runtime uniqueness" of MAC address based on devicePath does the job good enough and doesn't change the way how the MAC address is read with official DS4 gamepads.

### CODE REVIEW

**Comment by mika-n** [comment]
@Ryochan7 What do you think about this change in "MAC/Serial#" reading? 

If this fallback behaviour of using devicePath components as a serial#/MAC value then maybe doing this functionality to go through an optional configurion option for those people who need it and other would continue to use the old empty MAC code?  Anyway. Certain functionalities do require something like this to workaround problems of empty MAC address.

The best option would be if someone with one of those problematic after market controllers would debug how to read a real MAC address from those devices (but does it work with all other 3rd party controllers is still an open question).

**Comment by Ryochan7** [comment]
I have not had a chance to review this request yet. Been a bit too busy with other little adventures. I will try to get around to pulling and trying this change later today.

**Comment by Ryochan7** [comment]
That seems like it would be a good workaround for some third party controllers. It would be better to know why the serial check fails on certain controllers though. Performance seems good and it does not affect the way the Sony Wireless Adapter is detected. The serial number pulled from the adapter is blank when no controller is synced to it.

**Comment by Ryochan7** [comment]
Thank you for the change. This change has also been copied over to the WPF repo.

**Pull request merged**
