### PR TITLE
Added Czech translation.

### PR DESCRIPTION
**Pull request by Maikeru007**

### CODE REVIEW

**Comment by DragonZX** [comment]
IMHO you need to translate  DS4Windows/Properties/Resources.resx too

**Comment by DragonZX** [comment]
As for me. I've created https://www.transifex.com/opentranslate/ds4windows/dashboard/ maybe you find it useful

**Comment by mika-n** [comment]
Every now and then I have tried to take a closer look at those online translation web portals. It would make the life of non-developers a lot easier to contribute missing translation strings in existing languages or even to add new languages. How do you integrate translations made in Transifex with Github pull requests and resource files? Does it create diff patch files from changes or always submits the whole resource file? Or do you still use Github cmdline or VisualStudio tools to create a pull request?

Within VisualStudio I use "ResXManager" VisualStudio plugin to do resource translations. It is very easy to use and the master language (ENG) and other languages can be edited side by side and missing resource entries are automatically added when a missing translation string is added to non-master language. There is even a standalone version available for those people not using VisualStudio.
https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager

However, if translator doesn't use VisualStudio (sounds a bit extreme to install just to add and fix few missing translations) then they need to use Github cmdline tools to create pull-requests. Not obvious for people who don't do it already in other projects. 

How Transifex or other similar online translation tools work in this case? Can you create Github pull-requests directly from Transifex?

**Comment by DragonZX** [comment]
I need to make some research to answer completely, but:
Resources can be autoupdated from github (thanks, I have fogotten about this feature)
Also they have tx-tools to push translations to the project, but there is the first time I work with C# project in that case, usually my thanslationbs used by PHP/Python-based projects, where translations are updated by dev-server daemon.
First of all I've also tried ResXManager, but there are a lot of information, you are not using in your work. As for team translating there are no translation history, you need in some cases, but it was very helpful in some other cases.
As for now, I am downloading-commiting-pushing it manually, but there is no problem to do it automatically
Other info is reasonable to discuss privately

**Comment by DragonZX** [comment]
Oh, I've understood one of your questions) Usually all checks and commits making by the language rewewers team (or the one maintainer on his own risk), so the translatior itself doesn't need to install the whole VS, only if he watns to check or commit himself (but he may use more lightweight tools ie Jetbrains Rider).

**Comment by Maikeru007** [comment]
I will provide Resources.resx soon.

**Pull request merged**
