### PR TITLE
Added functionality to associate controllers to specific profiles

### PR DESCRIPTION
**Pull request by randu1459**
See:
[Ryochan7#69 - Would it be possible to associate profiles with controller ID? ](https://github.com/Ryochan7/DS4Windows/issues/69)

I'm not 100% sure what changed in DS4Form.resx. From what I can tell, some of this is related to the addition of the checkboxes, but I may need a more seasoned eye to tell me what's going on there.

### CODE REVIEW

**Comment by randu1459** [comment]
This weekend, I'll put my changes into a fresh clone of the project and see if I can figure out what I did to get some many changes into DS4Form.resx.

**Comment by Ryochan7** [comment]
The changes in DS4Form.resx seem to be layout related so I wouldn't worry about Visual Studio changing that file too much. However, the profile linking functionality does not work correctly. Profile association continues to be tied to the slot that is assigned to the controller even after enabling the link profile option. The link profile checkbox will be checked when DS4Windows finds the associated controller no matter which slot it gets assigned to though.

**Comment by randu1459** [comment]
Thank you for the feedback! I'll take another look at it when I get off
work today.

**Comment by randu1459** [comment]
I still need to look into the Xinput performance issue, but I see where I goofed up the rest of it. 

Currently, I've got DS4Windows finding and saving the profile when it should, but there was an issue loading it because I made an assumption about how the profile path was stored and was wrong (obviously). Basically, I was just calling LoadProfile and using the profile saved for the slot. I have fixed this.

I flat out missed the profile combo box. I thought it was updating correctly, but that was just poor testing. Updating the UI has been a little difficult for me, but I did some research and I also see how it's handled in other places within DS4Windows. I'm nearly finished with it, but I'll wait until tomorrow night when I'm a little more awake and can test more thoroughly. I'll make a commit when the base functionality is working and then work on troubleshooting the Xinput issues. If you have any suggestions to point me in the right direction regarding the Xinput performance, I'd greatly appreciate it!

**Comment by Ryochan7** [comment]
Lately, I just blame the JIT compiler when there is a small unwanted performance drop. I will always look back at this commit. One small change to an if statement made a big difference in performance despite having to technically perform more work for the common use case.

https://github.com/Ryochan7/DS4Windows/commit/39930cf2e8ea5a58e403ffec977a976fefa979f3

Getting the functionality working is more important. If nothing else, I will try to make some changes upon performing code review to tweak the performance of the program. Common things that I try are using private class fields to cache data used to define some local variables (it does help), minimizing property usage, using for loops instead of foreach in almost all circumstances, and caching list or array length in a temporary variable and use that variable in the test condition.

**Comment by Ryochan7** [comment]
I just tried some minor changes and found a quick solution. In the LinkCheckChanged method, removing Int32.Parse and using Convert.ToInt32 instead is enough to make a big difference. You can also take away the string cast in the process.

**Comment by randu1459** [comment]
Linked profiles should now be loading correctly. I fixed a few other issues that I ran into as well - mainly gaps where the GUI wasn't updating to reflect a profile change or where the GUI was updated with a change that didn't happen.

This has been a great learning experience. I spent quite a bit of time learning about making thread safe calls. I've still got a long way to go, but this has been very fun. 

This SHOULD be working now. Thank you for your time and your feedback!

**Comment by randu1459** [comment]
Hi @Ryochan7! I hope all is well! Do you have any more suggestions? It seems that most people are prefer a separate branch for changes like this. I'm not 100% sure that I understand why (surely my own ignorance), but I'd be glad to work on that if it will help.

**Comment by Ryochan7** [comment]
Making a new branch is not really necessary. When I pull the code on my system, I will create a separate branch for the changes anyway so that I can compare the changes with the current code. The only other benefit that I can think of would be having a cleaner git history.

This functionality only partially works on my system. The output LinkedProfiles.xml file does have the most recent profile listed for each controller mac address. However, the profile for slot 1 always gets changed as opposed to the slot the controller is being assigned to. Also, I am not sure if the extra event handling that is being done when saving the Profiles.xml file is really necessary. I don't see a reason to not add new fields to the BackingStore class instead of having to use event handlers to go back to the GUI to check the checkbox checked state for each slot.

**Comment by randu1459** [comment]
Thanks @Ryochan7! I'll have to grab another controller and figure out what I did wrong.

Honestly, once I learned to adjust the GUI from the background processes (I think there was one specific thing I needed this for), I'm think that since I had a "hammer" in my hands, everything started looking like a nail and I went happily smashing everything with that hammer. I'll simplify that using the BackingStore class.

I appreciate the time you put into this project as a whole and the time and patience you've given me! I'll see if I can simplify things during the week and look into the additional controller slots this weekend once I get my hands on another controller.

**Comment by Ryochan7** [comment]
Finally got a chance to check this out with a second real controller. The profile would always change for both controllers when the second controller would reconnect. The routine seemed to work fine when reconnecting controller 1 though.

**Comment by Ryochan7** [comment]
A version has been made with a different design. Testing seems to show that this version works with multiple controllers and performance is good.

**Comment by randu1459** [comment]
Thanks @Ryochan7! I believe this was a good experience for me even though I didn't get it working as hoped. I appreciate your patience and assistance! I will take a look at the new (working) implementation and see what I can learn from it.

**Pull request closed without merging**
