### PR TITLE
Fixed handling of "Left Alt" key in macro recorder (special system key event in some keyboard layouts)

### PR DESCRIPTION
**Pull request by mika-n**
LeftAlt key event is sometimes registered as Key.System event in RecordBox.UserControl_KeyDown/KeyUp(KeyEventArg e) record. The old behaviour left this as value=0 (VirtualKeyFromKey for systemKey event is zero), so LeftAlt was not recorded properly. Macro recorder showed it as "System" key which does nothing as VirtualKey VK code value.

This fix adds a special handling to System key if it is LeftAlt systemKey event. It is mapped as VK_LMENU virtual key code which is LeftAlt.

Issue #1000 more info about the issue. The following picture shows how LeftAlt was sometimes registered as e.Key.ToString=SYSTEM event and VALUE variable ended up being zero.  This fix re-maps this system key event as 164 VK_LMENU (=leftAlt) event just like any other key is registered in macro recorder.

DS4Win_MacroRecorderLeftAltSystemKey

### CODE REVIEW

**Comment by Ryochan7** [comment]
I'm sorry but this change did not work out. It required more code than necessary and still did not handle the RightAlt case.  I ended up making a comparable change that handles both edge cases.

Relevant StackOverflow page:
https://stackoverflow.com/questions/16668798/difference-between-keyeventargs-systemkey-and-keyeventargs-key

**Comment by mika-n** [comment]
RightAlt worked here fine even in the original code, but LeftAlt was registered as "system key" event. 

However, could be that different keyboard layouts handle these system keys a bit differently. For example Finnish/Swedish keyboard layout has three alternative chars in few keys (normal key press, shift key press and third one is for RightAlt (=labelled as AltGr in Finnish/Swedish keyboard layout) or Ctrl+LeftAlt combination). The code change I did handled those cases, but could be the for example US layout works a bit differently. 

I tested the slightly tweaked change you had committed in code base here with Finnish/Swedish layout and it works with LeftAlt key. However, now there are few more weird things.

TAB key is registered as "TAB down / LeftBumber up" event names. And RightAlt is registered as LeftCtrl+RightAlt combination. Return key is shown in the macro recorder list view as "Return down / Right Trigger up" key event names. The weird thing is that key value is stored correctly, so only the visible name is wrong. I believe those wrong names come from MacroParser.macroInputNames lookup table and for some reason macroStep object now accidentally uses that table as a lookup able for custom names.

DS4Win_MacroRecorder_SystemKeyWeirdness

**Comment by Ryochan7** [comment]
Checked again and RightAlt is registered as a system key on my machine and requires the tweak to register properly. Ended up encountering problems when pressing the Enter key so I looked into the issue. It turns out the big problem was due to the RecordBoxViewModel.ProcessDS4Tick method. The DS4Controls value was being checked in the keysdownMap rather than the adjusted macro value. Controller output for macros must have a value over 255 to not conflict with keyboard events in the macro routine.

The issue with extra macro steps being added should be solved. It works for me regarding the Enter key.

**Comment by mika-n** [comment]
Yes. Just found out also the reason why Enter/Tab and numerous other keys are registered wrong. Exactly just like you said ProcessDS4Tick method tries to detect key up/down status using the keysDownMap dictionary, BUT gamepad keys as DC values are used directly. Therefore code value 9 is TAB in keyboard, but it is also LeftBumper in gamepad. 

WinForms used DS4ControltoInt(dc) re-mapping table to re-map gamepad keys to 200+ key codes, so it didn't conflict. 

And while debugging this I realized why it worked earlier. I tested macro recording without connecting a gamepad, so there was no conflicts but now when the gamepad was connected there was a confclit in ProcessDS4Tick method.

**Comment by mika-n** [comment]
The latest fix in ProcessDS4Tick method solves the issue and now things work better. Also finnish/swedish kbd layout detects LeftAlt key properly which was the original issue. 

RightAlt is registered as "LeftCtrl+RightAlt" (ie. two key down and up events from one key press/release), but I'm sure this is Finnish/Swedish kbd layout issue because rightAlt is actually "AltGr" and it is the same as pressing LeftCtrl+LeftAlt key combination. This is not a major problem because if the extra LeftCtrl event is not wanted in RightAlt macro step then it can be removed from the macro sequence.

I will close this pull request because the issue is now resolved.

**Pull request closed without merging**
