### PR TITLE
Copycat

### PR DESCRIPTION
**Pull request by firodj**
Deprecating the PR: https://github.com/Ryochan7/DS4Windows/pull/1767

I've add new configuration field to enable these byte, when using copy-cat DS4.

CopyCatDS4CheckBox

### CODE REVIEW

**Comment by Ryochan7** [comment]
It too bad that a simple Feature Set flag workaround won't work here without also affecting real Sony DS4 controllers. I don't want to tackle this type of problem with a profile option though. It is too bad that this probably could not be a device specific setting as the process would occur too late.

Maybe that setting can be checked similar to how output report id checking is done now? One output report could be sent out with the flash flag set and the result would be checked. Then the output byte could be changed if the first write fails. I cannot find a post of you talking about what exactly happens when the 0xF7 byte is sent out. Is that approach possible?

**Comment by firodj** [comment]
In my case, when 0xF7 sent, there is no error/exception thrown, so we don't know if the controller support it or not other than see the light bar and rumble changes or not.

**Comment by joemdiente** [comment]
Hi @firodj, thanks for this commit. I tried it on my copycat ds4 and it works perfect.
Tested in DS4Windows 3.0.3 as I still haven't updated yet.

**Comment by xiaomengzaici** [comment]
Hi @firodj ,thanks for this commit.I wonder if you can extract this function and make a separate program.Because when playing the game on steam, this software will conflict with the controller program on steam

**Pull request closed without merging**
