### PR TITLE
Inter-process interface to do start/stop/shutdown/loadprofile operations from a cmd line. An autoProfile rule supports now both program path and window title as search 

### PR DESCRIPTION
**Pull request by mika-n**
Sometimes it would be useful to control the DS4Windows app status from an external batch file or application. 

For example, to stop/start DS4Win controlService thread or even to shutdown the app (ie. close) without interactively doing "Exit" via tooltray menu item. Or to load a specific profile using a batch file which launches a certain game (ie. the batch file chooses a game specific profile and launches the game in "one click").

Or if PC suffers from a high CPU load after the PC goes through sleep-resume cycle then a power management related trigger task could do stop/start or shutdown commands automatically as a workaround until the real cause of sleep-resume issue is found out. 

This pull request contains an inter-process communication interface between DS4Windows.exe executable and the "single instance DS4Win main process" running in background. It can be used like this:

- Launch DS4Windows application and leave it running in the background as usual
- Send commands to DS4Win background process from a BAT/CMD batch file or from your own custom application using the following command line syntax:
```
DS4Windows.exe -command stop
DS4Windows.exe -command start
DS4Windows.exe -command shutdown
DS4Windows.exe -command LoadProfile.1.SnakeGame     (syntax is LoadProfile.device#.ProfileName)
```

Following tickets are loosely related to this new feature, but is not a specific "bug fix" for those tickets, but a new feature useful for other cases too.
https://github.com/Ryochan7/DS4Windows/issues/733
https://github.com/Ryochan7/DS4Windows/issues/730

PS. the "-command" keyword needs to be in lower case letters . Other options are case-insensitive.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I'm not sure about this one. It could be useful to use with emulation suites but it really seemed like the original use case would not work out anyway. Once a BT controller is opened in DS4Windows, it will not be usable outside of DS4Windows until the controller is re-connected to the PC. One other thing about this implementation is that maybe shared memory can be used to hold the runtime class identifier for DS4Form rather than using a text file.

I will give this a try in a bit.

**Comment by Ryochan7** [comment]
Performance of the app suffers due to these changes. Looks like this will be a no-go for now.

**Comment by mika-n** [comment]
>seemed like the >original use case would not work out anyway. Once a BT controller is opened in >DS4Windows, it will not be usable outside of DS4Windows until the controller is re-connected to the PC. 

Jep. The main motivation for this new feature was not those "stop / start / plug-in / plug-out" a controller on the fly cases. Well, maybe the "-command shutdown" and re-launching DS4Windows.exe automatically based on a power management event might be useful in cases where resuming from a sleep state causes some weird behavior and re-launch of DS4Windows executable seems to fix it. 

In generally, more useful feature is a "-command LoadProfile.1.SnakeGame" cmd option to select a profile from a batch script which chooses a correct profile and launches a specific game. Then there is no need to use auto-profile feature which is a bit nasty (performance) about how it constantly polls the name of the foreground application window.

This IPC communication technique is very light weight for a simple data transfers because it didn't require any additional protocols or threads or listening "sockets" in DS4Win app (WndProc message queue is already used there). It would be also very easy to extend it to support new commands (fex start and stop UDPServer on demand from batch scripts). 


>One other thing about this implementation is that maybe shared memory can be used to hold the >runtime class identifier for DS4Form rather than using a text file.

Good idea. Shared memory block would be better way to store this DS4Win app specific value of WndClassName attribute. And it would be automatically gone when the main instance of DS4Win app is closed.

>Performance of the app suffers due to these changes. Looks like this will be a no-go for now.

Strange. The new feature didn't add anything to the main thread doing the actual gamepad reading stuff. Only addition in the "main process" was one WM_COPYDATA switch case option in WndProc method. This shouldn't cause any measurable difference even when in this case .NET compiler probably didn't optimize the switch case as a direct jump table as it often does if switch values are in sequence. 
 
I didn't see any performance difference, but I'll run few more tests. Sometimes .NET/CLR/compiler/runtimeEngine is a mystery how it optimizes apps. Difference in .NET framework version may have small differences in performance even when the code is identical.

**Comment by mika-n** [comment]
Changed the code to use memory mapped file instead of physical file to exchange the name of the DS4Form window class between processes.

I also test run and tried to see if the change makes the app slower, but could not see any difference. Didn't do any "scientific" performance analysing,, but just evaluated how the app felt and observed the latency of gamepad reading. No differences in performane as far I can see.

PS. Today Win10 in my laptop decided to update itself to the latest Windows10 version. HidGuardian stopped working, but re-installing it via DS4Win TestInstaller tool fixed the issue (this has been the case earlier also with HidGuardian).

**Comment by mika-n** [comment]
@Ryochan7  I made a major renovation to the auto-profile logic and auto-profile editor tab page. Now this pull request has following changes:

- Command line interface as described earlier in this post (ds4windows.exe -command LoadProfile.1.SnakeGame / ds4windows.exe -command stop/start/shutdown) cmdline interface for batch files. Especially LoadProfile cmd line option is useful with batch files which launch both a game and a chooses the correct profile without auto-profile tasks or user clicking any GUI selections.

- Auto-profile now supports both program path and optionally window title as a "match rule". 
- Auto-profile rules for path and window title "keywords" understand wildchars. ^ABC = match at the beginning of path or title string (^) | ABC$ = Match at the end of string ($) | *ABC = Contains a string (*).
- Auto-profile screen has a runtime option to send detailed auto-profile event messages to Logs tab page. This is very useful if/when an application is not that obvious what path or window title values it uses at certain scenario. For example Windows Store apps have the same program path, but just window title changes between applications.
- Auto-profile rule list now allows the same program path multiple times if rules have a different window title keyword. This way it is possible to support WinStore apps where different apps or scenarios use the same path but different wnd title. 

I also re-wrote the "check foreground process with a matching profile" function of auto-profile watch thread (runs once every second). Earlier it was very inefficient as far CPU cycles and RAM is considered. It did lots of buffer allocations and Windows API calls each time the auto-profile thread timer kicked in (once every second). This probably causes extra work for Net/GC engine. 

I optimized it to use caching to remember the previous window and processID/handle values. If the current active foreground wnd is still the same then the code no longer do buffer re-allocations and extra API calls each second. Now the auto-profile checking is very lightweight and fast if the foreground wnd is still the same.

DS4Win_AutoProfileEditor

**Comment by mika-n** [comment]
@Ryochan7  This pull request is release ready from my point of view. I think the new auto-profile logic makes this whole autoprofile thing a lot more useful than it used to be and it works much better (in terms of CPU performance and RAM consumption). For example WinStore apps are now able to use auto-profiling (those apps share the same application executable, so the old logic could not identify which WinStore app was actually running).

Also, the new inter-process command line interface to LoadProfile/stop/start/shutdown DS4Windows engine might be useful in cases where auto-profiling is not used but user wants to automatically choose a profile based on launched application. Stop/Start/Shutdown commands may be useful for those people where PC sleep cycle causes DS4Windows to consume lots of CPU power and only way to recover is to restart DS4Windows. A batch file doing shutdown and re-start could be attached to sleep/wakeup system events.

**Comment by Ryochan7** [comment]
Performance of the latest version looks good. The changes have been merged in. Thank you for these changes.

**Pull request merged**
