### PR TITLE
Fixed memory leak issues in ProfileEditor

### PR DESCRIPTION
**Pull request by kurtanr**
Fixes some issues mentioned in #3076

### CODE REVIEW

**Comment by Ryochan7** [comment]
I will have to look into this more closely. The Profile Editor reference is set to null after it is closed so no reference to the instance should exist afterwards. Those event references should go away as well so unregistering the events manually should not be required. Maybe all this is a side effect of the lax garbage collection being done?

**Comment by kurtanr** [comment]
Root cause of the issue might be a [binding leak](https://blog.jetbrains.com/dotnet/2014/09/04/fighting-common-wpf-memory-leaks-with-dotmemory/#binding-leak) - in the screenshot I sent, `PropertyDescriptor` is in the retention path.

I didn't want to go into the direction of implementing the `INotifyPropertyChanged` in view models, because as far as I see, none of them implement it right now - so I opted for a localized fix.

**Comment by Ryochan7** [comment]
The symptom is fairly similar but it does not seem to apply completely here. I never knew about using the `ValueChanged` event from `System.ComponentModel.PropertyDescriptor` but I would assume it only works for binding to auto properties; I usually use normal properties with backing fields and bindings have not updated by just updating the property. Rather than use `INotifyPropertyChanged`, I have used the `[PropertyName]Changed` event handler technique that WPF supports for updating bindings.

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/binding-sources-overview?view=netframeworkdesktop-4.8#providing-change-notifications

I have tried utilizing `INotifyPropertyChanged` on multiple occasions and found it adds performance overhead to the final executable even for simple cases.

Getting back on track, running the Performance Profiler in VS seems to show that the main issue is due to the lax garbage collection being done. There are times when many Profile Editor instances could still be in memory but memory usage and object count goes down a lot once those instances are finally purged.

The changes might help get those event references cleared from memory more quickly. I will check out the code on my end in a bit.

**Comment by Ryochan7** [comment]
It looks like memory usage increases more slowly with the changes. Got the changes merged in. Thank you for looking into this.

**Comment by kurtanr** [comment]
@Ryochan7 

Thank you for merging the changes.
Some additional thoughts from me...

**Regarding auto property vs property with backing field...**
There isn't really any considerable difference between the two, and I don't think that the `PropertyDescriptor` works differently if you have one or the other. Consider this block of code:
```C#
public class MyClass
{
    public string MyAutoProperty {get;set;}
    
    private string _myBackingField;
    public string MyPropertyWithBackingField
    {
        get{return _myBackingField;}
        set{_myBackingField = value;}
    }
}
```

If you look at the lowered code (code lowering is done during compilation) at [sharplab.io](https://sharplab.io/#v2:D4AQzABCBMELIE8DCAbAhgZwwWAFAG88JipIQBGABngQEEBXAFwHsAFAJ2YAcBTdxhBHwBzHowDcGMeIC+REvOJd2ASwBuaRjyhUIAfQC2CAEJoAxgGsVAO2EAxFTxQATcYtI7qiDtz4CA6iqMABamljb2ji7uhLgk8RCijPggAOz6RmFWtg5OrnJxCcRSyYYm5tmReRAAvBAaKPQ8su4FMkA===) you will see they are mostly identical - the only difference being that in case of auto property, you have a compiler generated (not manually written) backing filed.


**Regarding [PropertyName]Changed event handler technique...**
Can't say that I've ever used that and I'm not sure what the proper way to use it is (and if it is more susceptible to memory leaks). But even the page you linked says that "The recommended mechanism is for the CLR or dynamic class to implement the INotifyPropertyChanged interface". [This page](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged?view=net-8.0#remarks) also says that INotifyPropertyChanged is the "preferred" way to go.

INotifyPropertyChanged itself shouldn't be problematic - what may cause problems is if you are raising it too often (when it is not needed) or raising it for controls that take a long time to update. The same applies to [PropertyName]Changed event handler. One other issue that could cause performance problems when using INotifyPropertyChanged is if you invoke PropertyChanged with empty string or null - this indicates [all properties on the object have changed](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=net-8.0#remarks). This results with update of all the controls that bind to any of the object's properties.

Looking at the current implementation, isn't this the thing that is actually happening in all the ViewModels currently?
Shouldn't this:
```C#
public event EventHandler MainColorGChanged;
MainColorGChanged?.Invoke(this, EventArgs.Empty);
```
Be replaced with this:
```C#
public event PropertyChangedEventHandler MainColorGChanged;
MainColorGChanged?.Invoke(this, new PropertyChangedEventArgs("MainColorG"));
```

Anyway, thank you for merging the changes. But as I said, this is a fix for one particular control. I think that other controls also have similar issues which might be solved by either:
- implementing INotifyPropertyChanged in ViewModels (preferred)
- implementing [PropertyName]Changed event handler technique differently (as described above)
- manually analyzing all the retention paths and deregistering event handlers

**Comment by kurtanr** [comment]
Hi @Ryochan7 

I just tried your sample and yes, when using `[PropertyName]Changed` method, `PropertyChangedEventHandler` & `PropertyChangedEventArgs` are not needed (and actually do not work).

Additionally, when one property is updated, this does not cause all other properties to get updated. This means that `[PropertyName]Changed` method with `EventHandler` & `EventArgs` is not problematic, as I thought it might be (like calling `PropertyChanged` with empty string or null in case of `INotifyPropertyChanged` is). Learned something here 😊.

Updating backing fields instead of properties can result with better performance, especially if updating a property is raising `PropertyChanged` events. But this is a different topic from auto properties vs non-auto properties (updating auto property or non-auto property should result in the same performance).

I forked your sample and extended it a bit - you can try the sample here:
- https://github.com/kurtanr/PropertyBindingUpdateTest

If I try clicking on 'Add control' then 'Remove control' 10 times, memory usage goes from 90MB to 1250MB if checkbox is not checked. If checkbox is checked, memory usage remains at 90MB (or sometimes goes up to 220MB max).

The only difference is in the ViewModel that is used in the background (when checkbox is checked, ViewModel implementing `INotifyPropertyChanged` is used). Interesting results 😄.

**Comment by Ryochan7** [comment]
Got around to installing dotMemory and trying it out. It does seem to be better than the profiler tools included with Visual Studio. It does not seem to find any glaring memory problems that I can see. The only unsubscribed events that I see are ones for objects that are not disposed until the application stops. It might not be needed but I will make sure to unsubscribe from Timer.Elapsed before closing out a Timer instance whenever one is used.

I will take a look at your sample code later. That result does not make sense to me as it looks like any reference to the ViewModel or ProfileEditor should be cleared once the controls are cleared. I wonder if setting the DataContext to null before removing would help. And that code uses standard GC so the runtime should be performing garbage collection more frequently.

**Comment by Ryochan7** [comment]
large_allocation_retained_dotmemory

Looks like WPF keeps the final reference to the ProfileSettingsViewModel instance in its own collections. That snapshot was taken after the **Remove control** button was clicked. I have tested clearing the DataContext of all ProfileEditor instances before removing them from the DockPanel multiple times. That is enough to purge the internal references and allow .NET to reclaim the used memory. Guess I better start doing that for now on.

Not sure why it has to be explicitly done when using this technique but it looks like INotifyPropertyChanged does it automatically.

**Comment by kurtanr** [comment]
Great that you found a solution to the issue when using the `[PropertyName]Changed` method. These changes to the code should considerably reduce memory usage of the application. And I agree on your documentation comment.

**Pull request merged**
