### PR TITLE
Fix: Special Action > Disconnect BT

### PR DESCRIPTION
**Pull request by CJBok**
Special Action > Disconnect BT not working when using a Sony Wireless Adapter.

### CODE REVIEW

**Comment by Ryochan7** [comment]
The Disconnect BT Special Action works with my Sony Wireless Adapter. Based on the diff, it looks like the title would better be named Syntax Candy rather than Fix. There is no change in functionality. Just the removal of getter methods in favor of Properties in certain places.

I tested out the changes anyway and they confirmed my original justification for using getter methods in certain spots. Noticeable slowdown was introduced with the change. Based on my past experience with .NET, using Properites has a slight overhead compared to using a getter method so I tend to stick with getter methods for any routine that runs frequently. Properties are fine to use with methods that are only called sporadically.

I am sorry but I will have to reject this pull request.

**Comment by CJBok** [comment]
The fix is inside the Mappings file were an is exclusive check was performed.

If getter methods are preferred. I can revert the cleanup to use this instead.

I wasn’t aware on the performance difference. So thanks for this info.

**Comment by Ryochan7** [comment]
Missed the flag check removal with the convenient line break. Anyway, that check was put there on purpose. If Disconnect BT is allowed to run when Shared Mode is used, other applications will detect that the PS button is being held down until a controller is connected again or until the adapter is unplugged. That problem would mainly affect Steam.

Using the Special Action with a BT controller unplugs the actual device from Windows so there is no issue with a button being spammed there.

**Comment by CJBok** [comment]
Hmm I don't really get it. The DisconnectDongle method is called from 5 different places and this is the only place where this IsExclusive check is performed and thus preventing me to turn off my controller when I press the share+options buttons (or whatever button assigned).

Btw are you on a certain discord server to further discuss?

**Comment by Ryochan7** [comment]
Ended up going with another approach to the problem. Now the Disconnect BT Special Action sets a flag when the action is first triggered and the routine will check for all buttons to be released before the DisconnectDongle method is called. A BT connection will still disconnect when the action is first triggered.

The exclusive flag check has been removed as it is not needed as much anymore. A Guide button press would still be detected in Steam when using the default triggers but at least the Steam client will see a button release.

**Comment by CJBok** [comment]
Thank you! Will check it out as soon as the update lands.

**Pull request closed without merging**
