### PR TITLE
Customizable output curve functionality with a graphical web app to draw the output curve

### PR DESCRIPTION
**Pull request by mika-n**
New customizable (and graphically drawn) output curve for LS/RS/L2/R2/SX/SA analog axis. 

User can create any kind of output curves via an external HTML web app (see BezierCurveEditor subfolder in DS4Windows executable folder). Once the graphical curve in the editor looks OK then the "bezier curve definition" (list of 4 decimal numbers) string value can be copied to DS4Windows app. 

NOTE!: GUI doesn't have an edit field for this definition string value, yet. For now the value needs to be copy-pasted directly into a profile XML file (powered by Notepad). However, curve output needs to be set to a new "Custom" value in GUI.

In practice those old pre-defiend curves are also calculated using this new bezier curve functionality. Curve definition of those existing curves (Enchanced Precision, Cubic and so on) are just set to certain curve value to make the curve to match with the old implementation as close as possible. The graphical web app shows these DS4Windows default curves also.

BezierCurveEditor/index.html web app shows a graphical tool to draw the curve interactively. It also visualizes the "axis movement" (input vs output) to highlight how fast or slow the the output curve would be.

Technically this new feature also makes the output curve calculation super fast during a gamepad poll because the result is taken directly from a lookup table (axis raw input as index key to lookup table and a value as a re-mapped output value). The lookup table is calculated using the bezier functions only when a curve is changed (ie. normally when a profile is loaded).

DS4Win_BezierCurveOutput1

DS4Win_BezierCurveOutput2

@Ryochan7  What do you think? Is this something which could be included in DS4Win master branch? If this looks OK then I can finalize the implementation (field to enter the custom curve definition in GUI and a web link from DS4Windows Output Curve tabpage to the graphical curve editor and providing the existing curve definition as default value to the editor).

### CODE REVIEW

**Comment by mika-n** [comment]
As a reference here is a picture in GeoGebra to highlight how the output curve would look like with an old and new technique. As you can see those old pre-set curves can be replicated pretty accurately with the new customizable curve editor (in fact the result is a bit more smooth because the output follows a natural curve). I generated geogebra graphs from all old pre-set output curves and then draw the same curve in bezier editor. Those curve definitions are shown as an example values in the bezier web app editor. And by default the commited code uses those curve definitions, but the new "Custom" option allows to use any curve drawn in the editor app.

DS4Win_BezierCurveOutput3

**Comment by Ryochan7** [comment]
I have pulled the changes but only tested them a little bit. Performance is good. I will have to give the current code and this code a side by side comparison and test if I can feel a difference. The Enhanced Precision curve might feel different but I need to compare it to the current version.

Also, the temporary variables that were used in the old code was due to odd behavior observed in the past. For some reason, having a static variable assigned before assigning the temporary variable was faster than just using the temporary variable alone. I don't know why. There are some other minor portions of DS4Windows were that same hack was done. Luckily that oddity is not needed anymore.

**Comment by Ryochan7** [comment]
The newer curve option is pretty usable as is. Definitely an improvement over using something like a quadratic curve for manipulating a mouse pointer. The curve allows a mouse cursor to be usable in Civ 4. However, at least with the current setup, I still prefer the current Enhanced Precision curve. This feature is definitely a candidate for a custom curve option.

**Comment by mika-n** [comment]
Okey. Win-win case if I change the EnchPrecision option to be as it used to be with pre-defined ranges, but to make it also to work over look up table. Then other options and especially the new custom option would go through bezier curves.

I will also integrate the web app and Ds4win gui throug web link.

**Comment by mika-n** [comment]
@Ryochan7  This pull request is release ready. It now has the "old" mapping table for "Enhanced Precision" output curve, but at runtime this output curve goes through a lookup table also, so it should be faster logic during a gamepad state mapping. BezierCurve.cs file has the EnhancedCurve "lookup table initialization", so if that curve needs tweaking then it is also easier to do it through this file.

The profile options screen is getting a big crowded. I had to make a little bit room for "custom curve" editbox and weblink to curve editor in "Output Curve" tab page. When user selects a "Custom" curve option then the editbox and web link are enabled. The same editbox/link is user for all axies, but the "active" axis can be seen from a web link title. When user clicks an axis label or selects something from a dropbox then the label is updated to show that axis name.

At the same time I slightly re-located options in "Other" section because those were IMHO in a bit illogical order. For example, the "user control for mapping readings" has a logical place as the first or last option. Also, IdleDisconnect is related to hardware tweaks just like BTPollRate and Controller options. Those should be close to each other. Checkbox labels were also slightly misaligned.

DS4Win_OutputCurveOptions

PS. The "custom curve editor" web link tries to look for the current default browser and uses that to open the web page (with queryString parameters). If default browser config is not found then the app fallsback to use IE browser to open the web app. Naturally the curve editor webapp can be opened outside of DS4Win app also. (BezierCurveEditor subfolder in executable location. The new installer should remember to take this subfolder and index.html and build.js files).

**Comment by Ryochan7** [comment]
I have reviewed the latest changes. With the exception of the Enhanced Precision curve, all the other preset curves no longer match the output from the old routines. The only one I remember off-hand is the Cubic readings which accelerates faster on the low end than the old routine. Even Enhanced Precision feels different although the output coordinates seem to be mostly the same based on what I have seen. I am wondering if it just has to do with dealing with bytes instead of doubles so maybe some points will slightly differ.

As it stands, I have modified the mapping code to use the old routines for the preset curves and use the bezier curve for the Custom option. This would give more options to the user than just implementing a power curve option like I had thought about doing but never did. I will get the modified version merged into the repository shortly. Thank you for the changes you have been making to DS4Windows. This project would be at a complete standstill without your involvement.

**Comment by mika-n** [comment]
Calculations are done in double precision and just the result is byte casted. But it is true that I didnt tweak custom curves too much to match exactly those old curves except EnchPrecision. It should be exactly the way it was. But I think it would be good idea to change those old curves to go over lookup table as the enhprecision is now initialized using a dummy curve identifier. This way runtime should be better and the code is more clean and easier to maintain. I will test this and make sure the input-output mappping is the same before and after the change.

**Pull request merged**
