### PR TITLE
Fixed thread cleanup bug in the notification callback threads in ViGemClient (embedded into Nefarious.VigemClient.dll c#))

### PR DESCRIPTION
**Pull request by mika-n**
Fixed thread cleanup bug in the notification callback threads in ViGemClient. This fix is related to ticket https://github.com/Ryochan7/DS4Windows/issues/788

The original ViGemClient C++ code had a bug in cleanup logic of notification background threads. Notification threads are used in the VigemClient to send rumble and lightbar/led color commands from a game back to a gamepad.

The code changes of ViGEmClient c++ component are in the following fork of the original ViGemClient: https://github.com/mika-n/ViGEmClient 

These changes have been proposed as a pull request to ViGemClient maintainers (the original repository with a PR request: https://github.com/ViGEm/ViGEmClient).

The ViGem.NET project sitting between ViGemClient C++ project and DS4Windows c# client app didn't need any changes. As a reference that project is in https://github.com/ViGEm/ViGEm.NET repository.

This PR contains new pre-compiled (Release x64/x86) Nefarious.Vigem.Client.dll c# library files.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I don't think I can accept this as is. The multi-thread approach being used does not work for force feedback as testing showed before that there is the chance that the threads can be woken up out of order so the force feedback state would be wrong. Also, launching 20 backgrounds threads per controller to handle force feedback events seems like extreme overkill.

I like some of the changes made and the changes do address the zombie thread problem. I will do some testing to see if my old findings regarding that multi-thread approach are still valid.

**Comment by Ryochan7** [comment]
Unfortunately, I have confirmed that the initial findings are still valid. Console output on the delegate and rumble from RetroArch playing Legend of Zelda OOT using Parallel N64 core confirms it. I can see two times already when the reset state is sent to the delegate before an intermediate state (Full rumble -> Stop -> Heavy motor only).

**Comment by mika-n** [comment]
Okey. I can see now how and where the multithread waiting can randomly handle incoming notifications coming from Kernel Vigem vbus driver in wrong order if CPU "accidentally" switches an executing thread at "wrong cpu cycle" (or multithreading CPU handles those parallel threads few clock cycles in wrong order). Some games probably sometimes flood the FFB interface and then something like this could happen.

Those 20 listen threads were just something to play on safe to make sure there is always at least one DEviceIOControl waiting for incoming events because otherwise FFB events would be completely lost. The original ViGemClient used 20 threads also, so I took the number from there. However, if a thread doesn't have anything to process then it is consuming 0% cpu cycles because it is sleeping in WaitForMultipleObjects or in GetOverlappedResult(...., TRUE) call. 

I can take a look at this, so you can concentrate on other things. I took a second look at your VigemClient diff patch file and I can see how "interleaved" DeviceIOControl calls are used BEFORE the current overlapped handler calls GetOverlappedResult call and cycles through Notify1..4 objects. The fix I did does solve the handling of x360 and ds4 controller objects in a generalized code block instead of duplicating the code in two code streams, so it should be easy to maintain number of "interleaved" notify objects can be easily tweaked if necessary.

Fortunately there is a watchdog stop timer in rumble engine to stop the engine if "stop FFB" event is sent in wrong place, so the rumble motor won't get stuck in rumble state as it used to do when this bug first time appeared in Vigem client.

**Comment by Ryochan7** [comment]
The workaround that ended up being used was the first method that worked as expected. I remember trying to add a mutex to the old thread pool that was used and that didn't quite work out. The reason 4 overlapped structures ended up being used was because that seemed to be the minimum number of structs that were required to make force feedback from Parallel N64 work without getting in a stuck state; Rocket League worked fine with only 2 structs.

**Comment by mika-n** [comment]
@Ryochan7   I have now made tweaks to VigemClient C++ client code to workaround the "sometimes notification callback called in wrong order" issue. 

Here is a link to code changes if you want to take a look at it:
https://github.com/mika-n/ViGEmClient/commit/0b8756d522f2dee0de9d56e91b66671df3970066

And here a link to the committed vigemclient.cpp file itself if it is easier to see the "big picture" through it instead of looking at just a diff patch files (see vigem_register_notification_x360/DS4 and  functions).
https://github.com/mika-n/ViGEmClient/blob/0b8756d522f2dee0de9d56e91b66671df3970066/src/ViGEmClient.cpp

I have run several tests and no crashes (tested with LoadProfile batch file to force controller.Disconnect and controller.Connect calls to happen few times per second), no orphanage threads. Also tested with several application and no feedback callback method called in wrong order anymore (Dolphin emulator was one app which often flooded the IO queue and sometimes caused wrong ffb orders).

The new commit uses the solution you had designed in your change diff file (used cleverly just one background thread and pooled of IO requests) and adds there proper thread cleanup and generalized support for both x360 and ds4 controller types.

**Comment by mika-n** [comment]
Here is a link to pre-compiled x64 Nefarious.Vigem.Client .NET client library in case you don't bother to compile the vigemclient c++ and vigemclient .NET libraries from sources. The vigem client and .net library is a bit hassle to compile and very nasty thing to debug at development time.

[Nefarius.ViGEm.Client_x64.zip](https://github.com/Ryochan7/DS4Windows/files/3546227/Nefarius.ViGEm.Client_x64.zip)

If this looks good in your tests also then I will re-compile both x86 and x64 libraries and to re-commit those files in this PR. Unless you want to re-compile those and include in the master branch.

**Comment by mika-n** [comment]
Great. Do you wanna compile the new Nefarious.Vigem.Client.dll net library file for x86 and x64 platforms? In that case this PR can be rejected because at the moment those vigem dll files in this PR are old versions.

Nefarious has also accepted and merged the VigemClient changes into the master branch of VigemClient c++ package, so the master repository of VigemClient is now up-to-date also.

**Comment by mika-n** [comment]
@Ryochan7  This PR is now updated with the latest version of Nefarious.Vigem.Client.dll libraries with a fix to "sometimes notification callback called in wrong order" issue.

**Comment by Ryochan7** [comment]
Looks good. Got it merged in. Thank you very much for your work.

**Pull request merged**
