### PR TITLE
HidHide Integration

### PR DESCRIPTION
**Pull request by Yohoki**
Worked pretty hard to get HidHide integrated into D4W. No longer a need to leave the app to do anything having to do with HidHide.

More info on my issue tab https://github.com/Yohoki/DS4WindowsEx/issues/6

### CODE REVIEW

**Comment by Yohoki** [comment]
Merged main branch changes back into PR. Gives some build errors now from @Ryo's changes, but still builds nonetheless. Everything seems to work fine with any newer changes since v3.1.7

**Comment by Yohoki** [comment]
Hmm. Noticed a small issue... Something broke with the Auto-profiles. I'll need to look into this a bit. I didn't think I touched any of that. Was working yesterday I think, so I should have some idea where to look.

**Comment by Yohoki** [comment]
Ya. Odd... Something about merging the master breaks Auto-Profiles. I'll need to look a bit further into it.

**Comment by Yohoki** [comment]
Something about reverting the Change and then adding it back seems to have fixed it... Reverted the master changes to put my own changes through, but then adding back in the master changes to debug did not produce the error anymore.

But, I'm also not getting the random build errors that I was getting before. So Dunno what broke, but it fixed itself. Probably VS being weird.

**Comment by Ryochan7** [comment]
I will check this out later but I am a bit pessimistic about including it. Some bigger changes that I am not sure I want. Also including any new reference to an assembly is a massive gamble when it comes to app performance.

**Comment by Ryochan7** [comment]
> No longer a need to leave the app to do anything having to do with HidHide.

Leaving configuration to the HidHideClient was done on purpose. Makes it easier on me and it leaves problems isolated to the official tool. That should also help narrow down issue in the HidHide repo.

**Comment by Ryochan7** [comment]
The assembly reference is likely going to make this a no go. App performance drops big time with the changes and I have confirmed the assembly is targeting the AnyCPU platform.

**Comment by Yohoki** [comment]
I need to take some looks at it anyway. I'm noticing an issue with it atm. There's also a few things that I had done at the start of coding, and ended up changing later on as the HidHide DLL was made. I will probably need to just start from scratch. Should be easier now that I know where everything is and what needs changed.

> The assembly reference is likely going to make this a no go. App performance drops big time with the changes and I have confirmed the assembly is targeting the AnyCPU platform.

I'll have to look into this then. I just assumed VS would copy all of your settings when I loaded the repo into it. AFAIK, I was targeting x86 and x64. This is likely my fault for not knowing how to use VS. I'll try again now that I know this is an issue.

**Comment by Yohoki** [comment]
> > No longer a need to leave the app to do anything having to do with HidHide.
> 
> Leaving configuration to the HidHide Configuration Client was done on purpose. Makes it easier on me and it leaves problems isolated to the official tool. That should also help narrow down issue in the HidHide repo.

We will be butting heads here, then. As many issues popped up with Exclusive mode not working, or double inputs, or trouble setting up hidguard, and now also having to know how to set up HH... Figured it would be best to let it handle everything in the background. These options are optional, though. Those settings can be turned off so that HH can be configured entirely manually still.

**Pull request closed without merging**
