### PR TITLE
Language switch

### PR DESCRIPTION
**Pull request by czukowski**
Hi, I think I'm now ready to submit the language switcher (continued from feature request #169).

From the notable changes since then:

I haven't found a built-in way to find all available language assemblies without actually loading them all, nor getting the probing path from the runtime config section as it is apparently hidden. So I implemented a functionality for looking them up in the specified directories as well as exe directory in a similar fashion (the same string as in `probingPath` config must be set to the language picker control property - d0ad9d8) and it will additionally filter dlls by a specified name (ie `DS4Windows.resources.dll`) in order to skip assemblies for Task Scheduler - 300e842. Assemblies lookup will run asynchronously in order not to block other form elements from loading - acfb9b2.

One thing I kind of worry about are huge diffs to resx files even though I've added only 2 new keys to `DS4Form.resx` and one to `Properties.resx`. I think if you had made your changes to the resx files in the mean time, the changes would not merge...

### CODE REVIEW

**Comment by czukowski** [comment]
@Ryochan7 I noticed you changed language pack lookup in 1.4.109 release log; though I haven't looked at it closer yet, but I think I should modify the lookup method from this branch accordingly and make sure it uses the same logic.

**Comment by Ryochan7** [comment]
The language pack lookup change was just including the DS4Windows.exe.config file that is needed by .NET to use the Lang folder. Since the lookup had worked fine in the build output folder, I did not know about the file being necessary for that feature to work when bundling the program.

I'm sorry for being late reviewing this pull request. The changes perform well and the language switching works.

**Comment by czukowski** [comment]
No problem, I'm sure you've had a lot of other stuff to do.

Btw, some time ago I discovered a single language pack folder in DS4Windows installation directory besides the usual Lang folder and that by removing or renaming that folder I could see bare English UI. Since I was sure it wasn't me who had put it there, I assumed DS4Windows installer had done it at some point, and that it was a regular way of installing a language pack (there also used to be a checkbox in the Settings tab).

**Comment by Ryochan7** [comment]
There was a routine in the updater to install a language pack if the system locale was not set to English. That was removed because all the language packs are now bundled with the main archive.

Using the Lang folder setup is a little unconventional. The default way that .NET looks for language assemblies is to search the program's main folder for a language folder with a language assembly. I would not want to have the main folder cluttered with a bunch of language pack folders so that is why the alternative folder search is done.

**Comment by Ryochan7** [comment]
The Lang folder was not being used while searching for localization files. After debugging the problem, I found that the ProbingPath was not set before the localization scan would occur. Even though editing the usage of the LanguagePackComboBox class so that scanning was started later by DS4Form would probably be the better way to correct the problem, I took the easy way out and made the default string "Lang". That way I shouldn't have to worry about any unintended performance changes.

**Comment by czukowski** [comment]
Right, I must have missed that, sorry.

I tried to retrieve that value from App.config, but was unable to find a way, and the control property was kind of a workaround to avoid hardcoding the value. But since that values still ends up in the code, I guess that doesn't matter much anyway...

**Comment by czukowski** [comment]
@Ryochan7 sorry, I couldn't give it much thought earlier, but I think this should be improved. The purpose of the control property was to be helpful in event the probing path had to be changed at some point and provide a place to configure the value. But since it doesn't work properly, it's not helpful and may be even contra productive.

So I can see two possible solutions:

a) keep the hardcoded value and get rid of the non-working property altogether, _or_
b) delay populating the list box until after the designer generated code is loaded, essentially fixing the cause of the issue.

I don't believe any of these options has any potential to affect performance in any noticeable way as that code is being run only once on program startup and the scanning is being done asynchronously.

So if you agree on any of those above, I'm ready to provide the change in a separate pull request.

**Comment by Ryochan7** [comment]
Option a likely has no chance of changing the performance of the application. Option b would have to be looked at more closely as it could have performance implications. Personally, I would probably prefer to use Option b. I took the quick option beforehand since no real instruction change would occur.

Opting to change the loading order right away would likely have resulted in fighting .NET to get performance back to what I want. Like with commit 4fe6fc6660e4a6653a1e6c9373b8bb276c0a3122, it took a couple of hours after making the initial implementation to change the routine to get the .NET Runtime to behave the way I wanted; the initial implementation had a few more changes in Program.cs than the final version. As an example how things can go wrong, I like to refer to commit 39930cf2e8ea5a58e403ffec977a976fefa979f3 when switching the checks in an if statement somehow mattered to .NET even though the faster code meant both checks would always be performed.

Luckily it seems like these types of problems are becoming less frequent as more code changes are being implemented. For example, commit 86ee71e596045dcb49fc92d5603661a4a2648a60 resulted in a very noticeable performance improvement just based on changing timer usage.

**Comment by czukowski** [comment]
That is interesting, how do you measure the performance difference between two versions of code?

I noticed some kind of a CPU or memory usage graph in the Visual Studio, but that didn't look like a full-fledged profiler that would analyze execution tree and record execution times of every function. I must admit though that I haven't looked at it very closely.

My rule of thumb is that if the code in question runs in a timer tick or even in 'while' loop, then it is very sensitive as even a tiny change in the execution time would add up to a significant difference when measured per-second or so. But if the same change is introduced to a piece of code that runs only on startup, then nobody would probably even notice (not that it is an excuse for being inconsiderate when writing code, that's a whole different question). Then there is a so-called .NET magic, when a change in the code causes the performance to change significantly, while it is not apparent or expected from the nature of such change, and this is something that a code profiler would help solve.

**Comment by Ryochan7** [comment]
The main method of testing is just based on feel. Lately, my main games for testing input performance are .hack//G.U. and Gex. I do use the Visual Studio profiler on occasion to get an idea about what methods are called frequently and how much time is spent.

The timer that was changed is only actually run when the Scp Virtual Bus Driver is being installed using the Welcome Dialog. I have encountered other situations before that some routines that aren't even run have an effect on the final performance of the executable but I cannot remember any examples. Using a System.Timers.Timer instead of a System.Windows.Forms.Timer works out better for that situation anyway. There is very little UI updating occuring in the event handler so having most of the work being performed outside of the main UI thread is the better route to take; a BeginInvoke call is made for the few calls that update the UI.

**Comment by czukowski** [comment]
I added #218 as an attempt for a fix.

On an unrelated note, I'm just wondering, when testing the performance, aren't you worried that you may allow some random factors affect your judgment? Additionally, subtle changes in performance may be hard to notice without 'instrumental' measurements. I think this method must be quite hardcore to do it right :)

**Comment by Ryochan7** [comment]
There is that problem. The only recourse is to always make a diff with recent changes, revert back before a change was made, test the old state and then apply the diff and check again. I try to keep the system's state as similar as possible when running various build changes but that is not guaranteed. It is a pain to try to test changes manually all the time but other methods haven't been as helpful.

**Comment by czukowski** [comment]
I see... but there's gotta be a way to benchmark the code, otherwise it takes too much time and efforts to test performance. I googled up BenchmarkDotNet library, but although they say it's very flexible and powerful, in their 'getting started' guides they are suggesting to set up a new project and use some really simple code to benchmark, it is not clear for me how would one setup benchmarking of a critical part of DS4Windows code, such as [this large method](https://github.com/Ryochan7/DS4Windows/blob/39930cf2e8ea5a58e403ffec977a976fefa979f3/DS4Windows/DS4Library/DS4Device.cs#L638-L960)

**Comment by Ryochan7** [comment]
I am not sure if any automated tool would help with some scenarios that have come up while developing. There have been enough times when a simple refactor of code that isn't run in most cases has resulted in good performance improvements. I usually have check for updates disabled but commit 97110bad5a8b4926886ca69c443c9a60a4bf1326 led to an overall application performance boost that I did not expect.

**Comment by czukowski** [comment]
Of course not, covering 100% of the code would require an unreasonable amount of effort, but having covered those more important parts is beneficial. For example, it could be measured, based on, say, 1000 iterations, how much the controller input lag has been reduced on average after a code change you mentioned earlier. And somebody else could run that scenario on different hardware and compare the results. Of course, I'm not trying to convince you to change your development habits, especially since I've no experience with that particular tool and just talking in general. But I'm going to try it out and see if I can get anything practically meaningful out of that tool.

**Comment by Ryochan7** [comment]
I might have to add testing BenchmarkDotNet to my TODO list. Although, looking at the main page for the project, there does seem to be a big problem to start. The page states that the library supports .NET Runtime 4.6+ which is a problem for DS4Windows since it is currently using 4.5.2. I think I tested other .NET Runtime targets in the past and 4.6 would probably not be a problem but DS4Windows runs worse in version 4.7 for some reason. There have been no technical reasons to upgrade the version of .NET Runtime that is being targeted so the only upgrade has been to version 4.5.2.

**Comment by BibleBeliever** [comment]
So, to put it in simpler words, just install 4.5.2, right? Well, I'm glad I read this since I was always installing NET FW 4.7.

**Comment by czukowski** [comment]
@Ryochan7 yes, it appears to be far from a simple task. I've found an older version of BenchmarkDotNet (v0.10.3) that supported the 4.5 Runtime and added it successfully to the solution, but I didn't manage to do anything useful with it yet. Just briefly:

- If it is to be used as a tool to compare algorithms or two versions of the code (before and after), it would involve a lot of copying and pasting of the code and setup steps, and all this would be only temporary, until the 'winner' version is determined. This can be effective to compare relatively small parts of the code, but small parts give little information about the overall performance.
- For starters, I was hoping to set it up to test the 'actual' DS4Windows code, which would also involve a lot of setup steps, but it could be used as a sort of a 'monitor' for the development version. The issue here is that a lot of code can't be accessed that way because it's private or because there's a large method launches async tasks using inline functions. Also, there is a need of some mock objects, eg. simulating controller input, latency, etc, in order to help eliminate random factors in benchmarking. Some refactoring could help it, but I'm hesitant because of an unknown impact on performance just by refactoring and a risk of breaking something without realizing it.

To be honest, I haven't been able to give it a lot of time yet, and given the obstacles mentioned above, I'm letting the ideas to 'brew' in my head for the time being. If you get around to give it a try, I'd be glad to know about your findings.

**Pull request merged**
