### PR TITLE
Port to .NET 5

### PR DESCRIPTION
**Pull request by sitiom**
Deleted the fork so I can't reopen the previous pr (#1683).

### CODE REVIEW

**Comment by Ryochan7** [comment]
I'll take a look at your current progress. Took a stab at this myself today using some snippets from your previous pull request and some of my own experiments. Most components can carry over without much of an issue. It does look like there are some holdouts so far. Warning messages pop up regarding the following NuGet packages although they seem to still work right now.

```
Extended.Wpf.Toolkit 4.0.2
Hardcodet.NotifyIcon.Wpf 1.0.8
Markdown.Xaml 1.0.0
```

> warning NU1701: Package 'Extended.Wpf.Toolkit 4.0.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.

Although, the biggest problem NuGet package is WPFLocalizeExtension. The Markup Extension is busted as it rarely working in the current XAML Designer; it works fine at runtime though. The XAML Designer renders almost nothing for the main window due to many errors from failed lex:Loc calls.

There are enough changes to justify a different repo. I think I am pretty much stuck at this point.

https://github.com/Ryochan7/DS4Windows5

**Comment by sitiom** [comment]
> ```
> Extended.Wpf.Toolkit 4.0.2
> Hardcodet.NotifyIcon.Wpf 1.0.8
> Markdown.Xaml 1.0.0
> ```

There is a fork of Extended.Wpf.Toolkit with support for .NET Core in this fork:
https://github.com/dotnetprojects/WpfExtendedToolkit
Same for Hardcodet.NotifyIcon.Wpf:
https://github.com/HavenDV/H.NotifyIcon.WPF

> The XAML Designer renders almost nothing for the main window due to many errors from failed lex:Loc calls.

That is strange. It worked on https://github.com/Ryochan7/DS4Windows/pull/1875/commits/d8a3eea990dc0106129d99d75731d139ba29c9f0 before I merged the latest changes earlier.

**Comment by sitiom** [comment]
> ```
> Extended.Wpf.Toolkit 4.0.2
> Hardcodet.NotifyIcon.Wpf 1.0.8
> Markdown.Xaml 1.0.0
> ```

There is a fork of Extended.Wpf.Toolkit with support for .NET Core in this fork:
https://github.com/dotnetprojects/WpfExtendedToolkit
Same for Hardcodet.NotifyIcon.Wpf:
https://github.com/HavenDV/H.NotifyIcon.WPF

> The XAML Designer renders almost nothing for the main window due to many errors from failed lex:Loc calls.

That is strange. It worked on https://github.com/Ryochan7/DS4Windows/pull/1875/commits/d8a3eea990dc0106129d99d75731d139ba29c9f0 before I merged the latest changes earlier.

**Comment by Ryochan7** [comment]
I have those two updated packages linked now. Some other changes have been made in the repo as well. Ended up finding a string behavior change that affected the icon display for the Exclusive mode column; the key icon would never show up as the Hardware IDs for a device would be returned as a empty string. I will probably have to move that change to the current stable repo.

The XAML Designer issue is an odd one. Most XAML files work in the designer almost every time. ProfileEditor.xaml errors out almost 1 out of 3 loads. The MainWindow.xaml file errors out every time. I don't think I am doing anything wrong in those files. I can only hope that a future update to Visual Studio will fix some problems with the XAML Designer when working with .NET 5.0.

I have not done any play testing to check on the input performance yet. Need to get to that soon as any degradation of input performance would be a major deal breaker.

**Comment by Ryochan7** [comment]
That is odd. The controls render fine in the XAML Designer with commit d8a3eea990dc0106129d99d75731d139ba29c9f0.

**Comment by Ryochan7** [comment]
I guess I will have no choice but to rebase through every version of DS4Windows since that commit and stop once the XAML Designer breaks. So far, up to version 2.2.0.

**Comment by Ryochan7** [comment]
It looks like version 2.2.2 broke the main window. Profile Editor still seems to work at that version though.

**Comment by Ryochan7** [comment]
Commit 850e5b1500f4f315d6c88d6e7b4c2e98771064bf is the culprit

**Comment by Ryochan7** [comment]
Got the problem resolved and the ported 2.2.6 code now works. Funny enough, the core problem was the way the ImageLocationPaths class was set up. There were two issues with it when it comes to .NET 5.0 at least. Needed to change the access modifier and change the constructor. Profile Editor needs the latest WPFLocalizeExtension package which was being used in your version.  I was linking to version 3.6.1 due to a problem with a binding with a Browse programs button. Ended up having to change the Binding as well to make it behave correctly again.

Added App instance check to work around Design mode. Update WPFLocalizeExtension to latest version.
https://github.com/Ryochan7/DS4Windows5/commit/990ebf9313ac1c8aa7073683172f95b15e808faf

Fixed Browse Programs fallback value in Profile Editor
https://github.com/Ryochan7/DS4Windows5/commit/ed03949d4ac6158f6f4e087625b3a9a9295ace4c

Both of those changes would benefit the current stable DS4Windows repo so they will be included soon.

**Comment by Ryochan7** [comment]
Got those changes ported upstream to this repo. Next, I need to look at the command processing portion of the code and see why the changes you made were needed. I have not been using NetCoreBeauty in my test fork as I wanted to keep dependencies low to start with. That library would automate setting up a libs folder so I should test it out sometime.

Also, got around to play testing the port. It feels a lot better than the current stable DS4Windows so far. Faster input performance and definitely lower system load.

**Comment by Ryochan7** [comment]
Got around to testing NetCoreBeauty. It seems like it could be a useful utility but not really necessary. Found a way to exclude the translation assembly files so they can still contained in a separate Lang folder.

**Comment by Ryochan7** [comment]
Need to get back to this soon; hopefully it will be worked on after the current JoyCon experiments are over. With all the initial kinks worked out, it will be less difficult to go about creating a .NET 5.0 branch for this repo. For the most part, I really liked how DS4Windows ran when targeting .NET 5. It would be nice to have an updated fork to go along with updates to the .NET Framework 4.8 code base.

**Comment by Ryochan7** [comment]
Got a .NET 5 branch going with commit 81a1e53d017f5285be696ad45643c47f03a4d21c. Going to have to perform regular rebase commands to keep the branch in sync with the rest of the code base

**Comment by sitiom** [comment]
Thanks for completing this. I should reopen my PR on DS4Updater as well.

**Pull request closed without merging**
