### PR TITLE
Renamed/organized Virtual Controller related options on Profile/Other tab

### PR DESCRIPTION
**Pull request by Kanuan**
## Changes

- Moved Virtual Device related options to inside a new `Virtual Controller Settings` box
- Update  `Use DInput Only` Tip
- Renamed the `Use DInput Only` option to `Disable Virtual Controller`
- Added related strings to the `Strings.resx`
- Removed related strings from `resources.resx`
- Moved options to the top

image

## Shortcomings

The `Use DInput Only`/`Disable Virtual Controller` checkbox is associated to a variable named `DInputOnly`, which becomes true when the checkbox is checked. I wanted to make `Emulated controller` select box unavailable if the `Disable Virtual Controller` is active, but I don't know how to do so since if I were to use `IsEnabled` I would need to use **NOT**-`DInputOnly`, and I don't know how to use a not operator in WPF

Making changes to how the `DInputOnly` variable is used throughtout DS4Windows or creating a new variable would break existent profiles that have this option already enabled.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I had thought about doing something similar to this back once ViGEmBus support was first introduced. Ended up deciding to not worry about it then. That was probably back when DS4Windows was still using Windows Forms for the GUI and editing the code base ended up being much more of a nightmare back then. Weird performance issues would pop up for no good reason.

Except for maybe moving the GroupBox back down to around where the controls were before, this set of changes seems to be fine. As for performing a NOT operation for a binding in WPF, there is no direct option that I know of. Using a converter for DInputOnly would work to invert the value before the condition is checked; looks like the appropriate one would be the InverseBoolConverter. Adding another property to the ViewModel is always an option.

**Comment by Kanuan** [comment]
Because some users seem to outright miss the emulated controller option I thought that it would be better to move it to the top, but I will move it back down if you think it is more appropriate.

Regarding the NOT operation, I will look on how to implement the InverseBoolConverter since it may become useful in other parts of the code in the future.

**Comment by Ryochan7** [comment]
I should mention InverseBoolConverter is provided by WPF Extended Toolkit. It is not a standard converter provided by WPF; it is in package Xceed.Wpf.Toolkit.Core.Converters. I don't use converters much but they are used in some portions of the XAML in DS4Windows; most portions use custom converter classes I made. Here is an smaller example where a converter is used (BooleanToVisibilityConverter class).

https://github.com/Ryochan7/DS4Windows/blob/jay/DS4Windows/DS4Forms/ControllerRegisterOptionsWindow.xaml#L49

**Comment by Ryochan7** [comment]
Made a couple of small changes. The Strings.resx file was invalid due to a missing data end tag. Got the ComboBox disable portion taken care of using InverseBoolConverter. Thank you for the changes.

**Comment by Ryochan7** [comment]
Ended up changing my mind about re-positioning that GroupBox. Going to keep it on top of the Other tab like you had intended.

**Pull request merged**
