### PR TITLE
Encapsulate Left and Right Stick state into its own Stick class

### PR DESCRIPTION
**Pull request by SergejKiller**
This refactoring is needed to unify the code that handles transformation of left and right stick coordinates.

### CODE REVIEW

**Comment by Ryochan7** [comment]
Looking at the diff, I don't see the inherent need for this refactor. I can give it a try later but I don't see a reason, as of now, to commit it.

**Comment by SergejKiller** [comment]
Hi Ryochan7, 

This pull request is only a precondition. There will be more follow ups like:
https://github.com/SergejKiller/DS4Windows/commit/89d40bc7bfc94d32a21fd6d72002666b49bb6db3

I just don't want to send a huge pull request which is hard to review.

Sergey

**Comment by SergejKiller** [comment]
If you prefer a different way to submit multiple refactoring CLs please let me know. I'm new to GitHub.

**Comment by SergejKiller** [comment]
This is still relevant. The suggested refactoring will allow to handle left and right sticks by the same code. In the future I'm planning to do same the thing for Left and Right Triggers.

**Comment by Ryochan7** [comment]
Was never sold on accepting this. Closing this issue.

**Pull request closed without merging**
