### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by mentalsolin**
Hi, added translation only for translation files;
I can't compile the program, but I added and changed the translation lines as needed, I hope nothing is broken.

I found bug with \n in Strings.resx Ln 1290;
And it seemed to me that you made several typos in the file Strings.resx.

Can u add me to translations in About.xaml nickname "mentalsolin", thanks.

### CODE REVIEW

**Comment by DraakjeYoblama** [comment]
Bug with \n fixed in #3180

**Comment by mentalsolin** [comment]
Found a bug:
Other languages do not work in the WelcomeDialog window.

I have translation in ru, but I don’t see changes in the window.

**Comment by Ryochan7** [comment]
The WelcomeDialog window is loaded as a separate process and the DS4Windows config file is not loaded. Only the default app locale would be supported. It has been that way all along but that is a problem.

**Comment by Ryochan7** [comment]
Quick change to allow the set translation to be loaded in that case

https://github.com/Ryochan7/DS4Windows/commit/c55927c116824a1e560c9c43d2041802850d4688

**Pull request merged**
