### PR TITLE
Up to 8 controllers

### PR DESCRIPTION
**Pull request by grasmanek94**
I created this for myself but if anyone thinks it's useful, there ya go. Tested with 5 controllers and seems to work in X360 mode (all emulated X360 controllers work in joy.cpl).

Not extensively tested.

Please let me know if there are any other places with important magic "3" "4" or "5" numbers. The codebase is kinda hard to work on, so it's to be expected that I have made a few mistakes.

### CODE REVIEW

**Comment by grasmanek94** [comment]
Tested in Gang Beasts. Exclusive 5 controllers work.

**Comment by Ryochan7** [comment]
I guess I need to look into the maximum number of virtual devices ViGEmBus can create in one session. With ScpVBus, there was a hard coded limit of 4 virtual output device slots so there wouldn't have been much point allowing more input devices to connect.

The Steam discussion boards for Gang Beasts seem to suggest that using more than 4 XInput devices in the game is possible. It looks like the task would be easier if you were attempting to use Xbox One controllers rather than Xbox 360 controllers.

**Comment by grasmanek94** [comment]
>the task would be easier if you were attempting to use Xbox One controllers rather than Xbox 360 controllers.

Hmm is there some output mode I don't know of? I can only see this:

image


I ment to tell that using 5 genuine Sony DS4 Controllers, with option "Hide DS4 Controller" (and all exclusive access locks successful) is confirmed to work in Gang Beast. Maybe that's where the confusion came from.

**Comment by grasmanek94** [comment]
What would break anyway? The current release code disables any controllers higher than 4 so they won't work anyway. In this case one could add that check back or do nothing, as the behaviour probaly won't change. If the codebase was a bit less hard-coded stuff it would be trivial to implement dynamic adjustments for older OSes..

**Comment by BenHamrick** [comment]
Is there a way to tie this feature to a setting we can turn on in windows 10? I agree that this feature would be awesome. Who is honestly still gaming on windows 7 using a DS4? lol

**Comment by grasmanek94** [comment]
> Is there a way to tie this feature to a setting we can turn on in windows 10? I agree that this feature would be awesome. Who is honestly still gaming on windows 7 using a DS4? lol

I'm sure this would be possible but I don't get this fear about "Windows 7 compatibility being broken" - the first 4 controllers will always work. This code doesn't change _that_ functionality. Would need to test to be sure but I'm not going to install an unmaintained and unsecure OS on my network.

**Comment by Ryochan7** [comment]
Wonder what interesting behavior would occur once you add a 5th controller? Interesting lock ups and crashes occur when no XInput driver is available on Windows 7. Maybe something similar would happen.

Mainly two changes would need to be made. Firstly, DS4Windows would have a better idea about which version of Windows the application is running on. The second would be to then change the maximum number of supported controllers allowed in the app; at least enforce the limit in the ControlService.Start and ControlService.Hotplug routines. Most of the backend arrays can stay at the increased size. Besides, the fork needs to be synced to the current code to resolve merge conflicts.

> Who is honestly still gaming on windows 7 using a DS4? lol

More than you realize. Look at issue #922 for an example of people wanting continued Windows 7 support. I don't think this change is enough to justify breaking Windows 7 compatibility.

**Comment by Ryochan7** [comment]
Finally tried out the code. It fails the meritocracy test. Compared to vanilla DS4Windows 2.1.2, it runs much worse on my system. And I am going to mostly blame the Preparation commit. I use private backend fields for a few reasons rather than relying on auto properties.

https://github.com/grasmanek94/DS4Windows/commit/a58f11263dc5844045007dcfc3a50475557b504c

Not much point worrying about this issue anymore. Closing it now.

**Comment by grasmanek94** [comment]
If anyone ever needs 8 controller support you can use my branch: https://github.com/grasmanek94/DS4Windows/releases/tag/v2.1.7-8CE

**Comment by Ryochan7** [comment]
Let it be known, for the record, that I didn't ask for much.

> Compatibility with `upstream` will NOT be maintained anymore.

I doubt it.

**Comment by grasmanek94** [comment]
> Let it be known, for the record, that I didn't ask for much.

That's okay. It's just:

- No requirements specified as to what would pass off as a merge-able PR
- PR closed

This signals it's not going to get merged.

> I doubt it.

In the future more ugly code like `new Type something[4] = {-1,-1,-1,-1};` is going to spread through the codebase. It's a mess. It has to be refactored. 

The current version works fine with all games that I play with 7 - 9 other people on my machines. If it works, I probably won't touch it. With time, the forks will naturally become incompatible to merge in any direction. It's just to let people know they get the software 'AS IS'.

**Comment by Ryochan7** [comment]
Most of that mess comes from the old Jays2Kings DS4Windows 1.4.52 code base. The Mapping system used to be much worse but I have slowly grouped fields into classes as needed. Don't want to change too much at one time as performance issues come up out of nowhere when using .NET. It would probably be much easier if a Profile were seen as its own entity rather than the fields being a part of the BackingStore class. The long term goal is to move from DS4Windows entirely and make something a bit more controller agnostic.

8 controller support might be implemented at some point but it is still not a priority to me. I don't see myself working on it for a while; I barely have a need for 2 controller support. Maybe someone else will submit some changes that pass my standards. Not much of a point letting this thread continue. Locking it up.

**Comment by Ryochan7** [comment]
Now here is a version that currently falls in line with my standards. Besides the Win7 mess, the ScpVBus alt build gets updated every once in a while so a 4 controller maximum is still required for some use cases. Plus, the UDP Server protocol is hard locked at 4 controllers max. Those issues are taken care of.

https://github.com/Ryochan7/DS4Windows/tree/controller_bump

I will hold off on merging it into the jay branch.

**Pull request closed without merging**
