### PR TITLE
Russian translation 100%

### PR DESCRIPTION
**Pull request by DragonZX**
Russian translation fix

### CODE REVIEW

**Comment by DragonZX** [comment]
Is here any mistakes?

**Comment by Ryochan7** [comment]
The biggest problem is how Transifex included references to images despite not being overridden. For some reason, that also causes app slowdown. Looking over Transifex seems to be a bit limiting for the open-source project plan. 10 contributors might not be enough. I don't think I would use their service anyway.

I will get a Weblate account made and test it out with the DS4Windows files. I would rather use that service and it mostly seems like it would do the job.

**Comment by DragonZX** [comment]
I don't see any problem not to translate images (It may cause some slowdown in our situation). But regulary images also may be localisable, so that is not a bug.

**Comment by Ryochan7** [comment]
I would want those image entries to only exist in culture specific resx files if the image is overridden. Either way, the unjustified slowdown kills any chance of the translation being included. I will try to recreate the translation file and see if a manually created one works out.

I posted the following on another issue but it is relevant here as well.

> I am still waiting for a response from Weblate about an open source hosting account. Getting a free of cost open source hosting account requires manual review of this project to ensure that it is a true FOSS project. If I had my own VPS then I would probably just host my own instance of the Weblate software.

**Comment by DragonZX** [comment]
I've discovered Weblate interface, so Transifex IMHO is more comfortable for the translator, at least it displayed the size of the original string. Any way, personaly for me it's the tool I have 20+ projects without issues, so I'll be glad to see it as a tool for translators here.

**Comment by Ryochan7** [comment]
I usually prefer to go with a FOSS option over one that is proprietary. Transifex would require jumping through the same hoops to get an open source hosting plan but maybe they would be more responsive; Weblate warns that they might only check for requests once a month. There is no way I could even afford the Starter hosting plan on Transifex.

**Comment by DragonZX** [comment]
There are free 1000 strings plan after registering the FOSS project. I'm paying nothing for my FOSS projects. It needs only CVS link.

**Comment by Ryochan7** [comment]
There is no manual review required? That would make things easier. I am still not sure whether the 10 collaborator limit would end up being a problem. I guess I can at least make an account and take a look at the software.

https://docs.transifex.com/projects/open-source-project

**Comment by DragonZX** [comment]
I've no problem with it. 10 collaborator as I understand, means rewiewers and managers. There are no manual review needed, also I've translated some closed source projects using only pot files on github

**Comment by Ryochan7** [comment]
Gave Transifex a try. The interface is decent and easy to work with. However, the major downside still remains regarding the generated resx files. I could look past not being able to omit the image resources in the generated files. The unwanted slowdown is something I cannot look past. I notice slowdown just navigating DS4Windows but play testing shows input latency is affected as well.

It does not look like Transifex will do what I want it to do. I'll have to go back to manually editing the current source files a bit later.

**Comment by Ryochan7** [comment]
Experimented and it seems the BOM really matters in the XML files. Just inserting that code at the beginning of the file was enough to get performance where I wanted it. Weird.

https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by DragonZX** [comment]
It depend on mb_string function of target language, for the GUI application, overall detection of multibyte encoding may give a lot of perfomance.

**Comment by Ryochan7** [comment]
Thank you for the updated translation. Got the changes merged in but I found a side effect of the Transifex files that I do not like. Having the images referenced in other language packs makes full copies of the image data while compiling. That really bloated the file size of the zip file for version 2.0.7. Funny enough, the 7-Zip archives only increased a few KB.

With all the manual intervention that would likely be required to change the generated files, I don't think using Transifex for localization work will be feasible. I have still not gotten a response back from Weblate. Maybe a project for the weekend will be to get a dev server set up on my machine and test the Weblate software there.

**Comment by DragonZX** [comment]
I don't sse any problem in that case. First of all we can markup BOM in the english resource file, so will no need to edit translations manually. Is there an ability to separate text and images into different resx files?

**Pull request merged**
