### PR TITLE
Added a Norwegian Bokmål translation

### PR DESCRIPTION
**Pull request by DandelionSprout**
I've attempted to create a Norwegian translation of DS4Windows this afternoon.

It wasn't easy for me to figure out which files I should copy/create, which strings I should translate, and so on, so I can only assume that I did a decent job with it.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I don't know why but app performance is worse with these changes applied. The resource files don't seem to be formatted like the other lang resource files either. In its current state, I cannot accept this pull request. Sorry.

**Comment by DandelionSprout** [comment]
I'll take an unqualified guess that the performance tank was due to me not removing any of the coordinate/meta strings in the translations.

While I consider myself to be pretty good at translating programs, .resx is pretty much witchcraft to me. You can see if it goes any better now; if not, then I'd have to throw in the towel on this one.

**Comment by hydraheim** [comment]
There are phrasings here that actively translate the originals word-by-word.

"&lt;type profile name here&gt;" -> "Skriv inn navnet til den nye profilen her"

Instead of "Skriv inn profilnavn"

Furthermore there are translations that contains spelling errorsare simply wrong.

"Trinn 3: koble til DualShock 4-kontrolleren
For å sette opp med kabling/USB:
Bare plugg en MicroUSB-kabel til PCen og DualShock 4"

Instead of 

"Trinn 3: koble til DualShock 4-kontrolleren
For å sette opp tilkobling med USB: Koble en MicroUSB-kabel mellom PC-en og DualShock 4"

**Comment by DandelionSprout** [comment]
As much as I like to think of myself as being a skilled translator, I must admit that you're correct about both examples.

I translated the initial 5 files in somewhat of a hurry, as I at the time was less than certain about which files/strings I had to translate, leading me to write on my keyboard on autopilot to see how many strings I actually had to translate or not.

Now that I've removed superfluous lines anyway, that should give me enough of an overview to do a bit of an overhaul of the largest files I did.

**Comment by Ryochan7** [comment]
Can you commit the changes from DS4Windows/DS4Windows.csproj?

**Comment by DandelionSprout** [comment]
I am currently partway through a week-long vacation, so I'd be dependent on access to a stable Wi-Fi connection where I know that I can edit that file's language codes (presuming that it's what you intend for me to do) for up to half an hour on my somewhat small Lenovo phone. The very earliest I can do so tonight would be ~17:00 UTC.

**Comment by DandelionSprout** [comment]
Okay, so I've now commited the change you had made in https://github.com/Ryochan7/DS4Windows/commit/3473fe1dc9576ef67fadafe688d2810e95d45266#diff-7497ddfad9fb3defb21dd4485ea80e78, and added some Norwegian Bokmål language codes to the places I've thought they had to be added to.

**Comment by Ryochan7** [comment]
I pulled that latest changes and I encountered the same issues. The main problem is that the new translation files were not added to the DS4Windows.csproj file. After that change was made, the files show up in the solution like the other translation files and app performance is on point. With the extra change, this is ready to merge.

**Comment by Ryochan7** [comment]
Thank you for the updated translations. The changes have been merged.

**Pull request merged**
