### PR TITLE
Build: Update NET Framework Version on 4.8

### PR DESCRIPTION
**Pull request by Zangetsu38**
- Fix build with using last version without re target manualy and also without delete any code.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I am not sure about this one. Normally, some technical reason would be the main justification for updating the target .NET Framework version used in the project. .NET Framework 4.6.2 is primarily targetted due to the use of the HttpProgress NuGet package which uses .NET Standard 2.0. The minimum supported .NET Framework version that supports the .NET Standard 2.0 API is version 4.6.2. Although, the footnotes recommend new projects to target at least .NET Framework 4.7.2 for better compatibility.

https://github.com/bloomtom/HttpProgress

I can give the change a try and see if there is any real difference when using .NET Framework 4.8. If there is a boost in performance when targetting that .NET Framework version then that might be enough justification for updating.

**Comment by Ryochan7** [comment]
I finally pulled the code and tried it out. DS4Windows does seem a bit more snappy when run under .NET Framework 4.8. From what I can find regarding changes in .NET Framework versions, there is no new feature that would warrant an update. Also, .NET Framework 4.8 is available for Windows 7 users so that would not impact people still using it. Going to need some time to think about including this.

**Comment by Zangetsu38** [comment]
i see, but in my side, is obligatory need dump target version on 4.8, using 4.6.2 just get broken build and no works

**Comment by Ryochan7** [comment]
The changes have been merged in. I guess having access to the updated JIT compiler is enough justification for updating the target .NET Framework version. Thank you for the update.

> **Improvements to the JIT compiler**. The Just-in-time (JIT) compiler in .NET Framework 4.8 is based on the JIT compiler in .NET Core 2.1. Many of the optimizations and all of the bug fixes made to the .NET Core 2.1 JIT compiler are included in the .NET Framework 4.8 JIT compiler.

https://docs.microsoft.com/en-us/dotnet/framework/whats-new/#clr48

**Comment by Zangetsu38** [comment]
thx

**Pull request merged**
