### PR TITLE
Add Udpserver so that external applications can access raw motion and trackpad data

### PR DESCRIPTION
**Pull request by rajkosto**
Mainly just so people don't have to use my fork for https://sshnuke.net/cemuhook/padudpserver.html anymore
Since you've pretty much merged everything other than the udp server from my other branch, this only includes minimal changes needed to integrate udp server in (and optional crc32 check on calibration data, which is recommended and used by official drivers, if you dont like it then just dont merge that commit in)

Fixes https://github.com/Ryochan7/DS4Windows/issues/98

### CODE REVIEW

**Comment by JarnoVgr** [comment]
@Ryochan7 Just wondering: why do you not want to merge this in? Thanks in advance.

**Comment by Ryochan7** [comment]
I stated my objections before and they still have not been dealt with. The biggest problem is the additional input lag that results from the changes. One big philosophy affecting this project is that any change that results in a significant increase in input lag is not worth incorporating. The input lag issue also affected the delayed inclusion of any form of gyro calibration support. I had to implement a few different prototypes before I eventually was able to make a version that performed well enough. Unlike what had been speculated, it has been proven that work could have been done to get the feature working without adding any real latency.

Another big problem that had occurred before is that rajkosto broke features and then expected me to fix problems that he created. The big one was changing the code for Gyro mouse support, mostly for no good reason, and breaking that functionality. I had changed the Gyro mouse routine around that time and that made the problem even more frustrating.

I should not have but I downloaded the 1.4.97 patch build and gave the changes another chance. The changes still suck. My build of version 1.4.97 works fine and that version includes gyro calibration support. One other big problem that I notice with the build is that the native architecture decision that I made months ago has been thrown out the window. CorFlags shows that the program is an AnyCPU build rather than an x64 build like I have been releasing.

**Comment by JarnoVgr** [comment]
Thanks for taking a look at it again and explaining it to me. :)

I thought it was a good idea to merge this because of Cemu's popularity, which could benefit this project as well. But I understand you only want proper PRs. :)

**Comment by Ryochan7** [comment]
This adventure has finally ended. Version 1.5.3 has the UDP server integrated into the main program build. Only some of the most recent changes made to the code got performance to the point where I wanted it. I know I gave you a hard time but thank you @rajkosto for creating the server code.

**Pull request closed without merging**
