### PR TITLE
Add AntiFlicker

### PR DESCRIPTION
**Pull request by JADERLINK**
Adds a new option in "ProfileEditor" called "AntiFlicker" (I don't know if it's a good name), explanation of the function with image:

my control without AntiFlicker:
https://imgur.com/yOxz8M0

my control with AntiFlicker active:
https://imgur.com/YlWKGV9

Translate from Portuguese-Brazil:

Como visto na primeira imagem meu controle tem um problema de ficar tremendo, então fiz essa modificação para corrigir este problema.
Pelas minhas pesquisas pela internet vi que outras pessoas q tinham este problema, mas não encontrei nenhuma solução pra resolve-lo.

Infelizmente os valores de LX, LY, RX e RY são em bytes (pelo menos foi os que eu encontrei), ao ativar uma das opções de AntiFlicker a uma perda de sensibilidade do analógico, nas ultimas 2 opções é uma método meio termo, onde pode tremer as vezes, mas não tira muito da sensibilidade.

### CODE REVIEW

**Comment by Ryochan7** [comment]
I'll have to try this out in a bit. Having a minor amount of flicker present is not a big deal to me. It might be worse for other people depending on the condition of the controller.

**Comment by Ryochan7** [comment]
Tried it out for a little bit. I don't really like the feel of the sticks when it is enabled. There seems to be a pronounced delay compared to when AntiFlicker is disabled. Also, the changes in general cause some app slowdown even when the option is turned off for both sticks. This idea can be looked into further but I cannot accept the changes as they are now. More work will have to be done.

**Comment by JADERLINK** [comment]
Translate from Portuguese-Brazil:
Atualizei meu 'fork', coloque a minha adição em 'Mapping.SetCurveAndDeadzone', para reduzir o atraso.
Respondendo seu ultimo comentário: caso seu analógico (sticks) estejam bons, realmente não faz sentido usar o Antiflicker,  diferente do meu controle como visto na primeira imagem.
Sobre a lentidão no aplicativo: mudei a minha implementação de lugar, para ver se não mais afetará o desempenho do  aplicativo.
(Fiz 2 'Commits', pois ainda não seu usar 100% do github)

**Comment by myfunc** [comment]
Hi! Nice fix. 
Could you add AntiFlicker for Gyro (Sixaxis)? 
I use Gyro instead of left stick for racing games. It is really more convenient than stick, but sensor's shake breaks my pleasure little bit.

**Comment by Ryochan7** [comment]
Looking at all the array access occurring in the AntiFlicker class, it is not surprising that the routine seems to run slow. I need to check how Linux handles its fuzz setting for evdev devices. It would be nice to have some type of anti-flicker support for the 360 Steering Wheel mode. It is not a big deal but it would be nice to have a slightly smoother steering wheel in Euro Truck Simulator.

**Comment by Ryochan7** [comment]
Did some minor testing with 360 Steering Wheel mode and adding a small fuzz routine. The experience was definitely smoother although I think I used too large of a delta value for the test. Couldn't actually find any implementation docs regarding the Linux fuzz implementation (only evdev API docs). Testing for max, min, and delta seems good enough though; I also tested for center value but I am not sure it is needed.

**Comment by Ryochan7** [comment]
I need to look into this functionality again shortly. The implementation would have to be different so this pull request would not be merged in. Rather than the various modes offered in this version, I think just offering a simple delta value and working off of that will be good enough.

**Comment by Ryochan7** [comment]
It seems to work out fine but I still don't know if I will use it in the future. It seems to work fine in Deus Ex: Human Revolution but I have only tried it for a few minutes. I need to try to game a bit more with at least a 1 fuzz value used in a profile. A new release with the fuzz feature will be released soon.

**Comment by Ryochan7** [comment]
Version 2.1.8 has been released and it includes this feature. Thank you for the original code and bringing up the idea.

https://github.com/Ryochan7/DS4Windows/releases/tag/v2.1.8

**Pull request closed without merging**
