### PR TITLE
Use DetermineConnectionType in PostInit of DS3Device

### PR DESCRIPTION
**Pull request by sunnyqeen**

### CODE REVIEW

**Comment by clau007** [comment]
Hi @sunnyqeen, thanks for your contributions :) I've tried Dualsock 3 in SXS mode. DS4Windows is able to detect It fine through USB, but not through Bluetooth. Any idea why?

**Comment by sunnyqeen** [comment]
you need https://github.com/ViGEm/BthPS3
to connect with Bluetooth, 
it's not related with this pull request

**Comment by clau007** [comment]
> you need https://github.com/ViGEm/BthPS3 to connect with Bluetooth, it's not related with this pull request

I'm using BthPS3 already and It's working fine with DualShock 3 in SXS mode (I use It with PCSX2), but DS4Windows is not able to detect It when in Bluetooth and SXS. With USB and SXS, DS4windows is detecting It fine. Is It normal?

**Comment by sunnyqeen** [comment]
I have no idea, it should work the same way.
My controller works fine with Bluetooth.
You may need to debug the app yourself to see why it's not listed.

The hardware id showed in windows device manager should be similar like
BTHPS3BUS\{53f88889-1aaf-4353-a047-556b69ec6da6}&Dev&VID_054C&PID_0268

**Comment by clau007** [comment]
> I have no idea, it should work the same way. My controller works fine with Bluetooth. You may need to debug the app yourself to see why it's not listed.
> 
> The hardware id showed in windows device manager should be similar like BTHPS3BUS{53f88889-1aaf-4353-a047-556b69ec6da6}&Dev&VID_054C&PID_0268

Mine looks like this, It's a genuine DS3 controller:

BTHPS3BUS\{53f88889-1aaf-4353-a047-556b69ec6da6}&Dev&VID_054C&PID_0268\9&1df04c6&0&BTHPS3_DEVICE_01

image

**Comment by Kanuan** [comment]
Make sure you are on the latest BthPS3 version

There was a change recently on DS4Windows that made it try to better detect if a device was real or virtual. If DS4W detects the device is virtual then it ignores it. Unfortunately, older versions of BthPS3 made the DS3 appear as if it were a virtual device, with this issue being fixed on newer version

**Comment by clau007** [comment]
Upgrading BthPS3 to 2.6.174.0 did the trick, now It works in bluetooth mode as well. Thanks! :)

**Pull request merged**
