### PR TITLE
Fix DualSense not being recognized when connected via USB after connecting via Bluetooth.

### PR DESCRIPTION
**Pull request by nicolas-siplis**
When attempting to connect the DualSense via USB after having already established a connection via Bluetooth, the following exception message was being thrown:

"An item with the same key has already been added."

This PR does some dirty hacks to remove the duplicate DualSense devices (the same device was previously being added twice to the internal Dictionary). Starting/Stopping DS4Windows might be required to detect a change of connection from BT to USB and viceversa.

### CODE REVIEW

**Comment by Ryochan7** [comment]
This seems more like a hack to a Windows BT stack issue than anything else; I have experienced this type of issue only recently and I have experienced it with the Switch Pro controller as well. Windows sometimes has decided not to disconnect BT devices so it is still seen as live until the BT adapter is unplugged or Windows is rebooted. Haven't encountered the issue in a while but I believe that a different serial number (non-blank) is obtained in that scenario for some reason.

Also, I am not convinced this change does the stated job. It looks like the first check will remove all connected BT DualSense controllers provided that at least two DualSense devices are detected. This change would only work successfully and ignore the BT connection if only one DualSense controller is connected to Windows. Having multiple BT connected DualSense controllers would cause the check to exclude those devices entirely even when no USB connection is present.

**Comment by nicolas-siplis** [comment]
@Ryochan7 I think the serial generation you are referring to happens in HidDevice.cs:550

`serial = $"{MACAddr[0]}{MACAddr[1]}:{MACAddr[2]}{MACAddr[3]}:{MACAddr[4]}{MACAddr[5]}:{MACAddr[6]}{MACAddr[7]}:{MACAddr[8]}{MACAddr[9]}:{MACAddr[10]}{MACAddr[11]}";`

IIUC, the generated serial is being created twice when trying to connect via USB after Bluetooth, which causes the duplicate key exception in the serialDevices Dictionary in DS4Devices.cs.

Regarding the potential problem assuming multiple DualSense devices are connected, I assumed the following line would filter different devices correctly:

` .Where(hDevice => hDevices.Select(x =>  hDevice.Attributes.VendorId == x.Attributes.VendorId && hDevice.Attributes.ProductId == x.Attributes.ProductId).Count() > 1) // Only consider duplicate devices`

I'm guessing the problem is that different devices can have the same ProductId/VendorId combination? What would be the correct way to filter separate devices, ignoring if their only difference is their ConnectionType?

**Comment by mika-n** [comment]
> @Ryochan7 I think the serial generation you are referring to happens in HidDevice.cs:550
> `serial = $"{MACAddr[0]}{MACAddr[1]}:{MACAddr[2]}{MACAddr[3]}:{MACAddr[4]}{MACAddr[5]}:{MACAddr[6]}{MACAddr[7]}:{MACAddr[8]}{MACAddr[9]}:{MACAddr[10]}{MACAddr[11]}";`
> I'm guessing the problem is that different devices can have the same ProductId/VendorId combination? What would be the correct way to filter separate devices, ignoring if their only difference is their ConnectionType?

This logic to generate "unique" serial number for the connected gamepad (unique within the PC while gamepads are connected, not globally unique) is a fallback logic when for some reason the BT connected device doesn't have a real BT MAC address (usually all of those should have one) or DS4Windows app failed to read the BT MAC address (some incompatible HID message structure).

The fallback logic uses the Windows HID device path to generate the unique serial# because no two devices connected at the same time should have identical HID device path value. ProductID/VendorID (VID/PID) could be and often is the same when two DS4 or DS5 gamepads are connected, but the HID device path should be different (that's how WinOS knows who is who).

The fallback serial comes from the device id and from BT/USB host port because at least with USB devices you usually don't have two gamepads connected to the same usb port at the same time. With BT hosts the story may be a bit different because the BT host remains the same, but it should still assign different client ID (last remaining parts of the HID device path value).

What are the full HID device path values for those two DS5 gamepads when you connect those at the same time? Debug version of DS4Windows should dump out those values or you can add logmsg printout on your own fork. Somehow the ReadSerial method should be modified to create unique serial# string values for those gamepads if it fails to do it now.

Here is a link to the latest debug version showing lots of detailed log messages when a gamepad is connected and how that ReadSerial method tries to come up with a unique serial# value.
https://github.com/Ryochan7/DS4Windows/wiki/Troubleshooting#detailed-debug-log-file-from-gamepad-connection-problems

**Comment by nicolas-siplis** [comment]
> What are the full HID device path values for those two DS5 gamepads when you connect those at the same time?

USB connection: \\?\hid#vid_054c&pid_0ce6&mi_03#8&2cd70878&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

BT connection: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&0ce6#9&28da590b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

So, assuming the last part of the device path is unique per device, I suppose the following change would ensure that duplicate device connections are filtered correctly:

Previously:
`.Where(hDevice => hDevices.Select(x => hDevice.Attributes.VendorId == x.Attributes.VendorId && hDevice.Attributes.ProductId == x.Attributes.ProductId).Count() > 1) // Only consider duplicate devices`

Now:
`.Where(hDevice => hDevices.Select(x => hDevice.DevicePath.Split('#').Last() ==  x.DevicePath.Split('#').Last()).Count() > 1) // Only consider duplicate devices`

**Comment by nicolas-siplis** [comment]
@Ryochan7 any particular reason why this was closed?

**Pull request closed without merging**
