### PR TITLE
Add support for Nacon Revolution Pro Controller 2

### PR DESCRIPTION
**Pull request by Yuki-nyan**
Adding support for the new controller was just a matter of adding the PID, but I thought I'd try and tackle another issue I'd noticed too...

Neither Nacon Revolution Pro Controller implements gyro calibrations in the same way as the official DS4 so SixAxis support has been completely broken since version 1.4.97. I've implemented an initial workaround here by skipping over the application of calibration data to Nacon controllers while I investigate further.

Because Nacon controllers have an invalid MAC address PadTest always shows them as disconnected when using a udpserver build, however they still work if you use the "By Slot" rather than "By MAC" option in Cemu.

### CODE REVIEW

**Comment by Ryochan7** [comment]
Although the initial code caused some unwanted slow down, I have tweaked the routine a bit and it seems to work better. I will get this code merged and add the tweak as a separate commit.

**Comment by Ryochan7** [comment]
Thank you for the change. I don't know why .NET was acting temperamental before but at least the tweak didn't take long to implement. This change might come in handy for other third party controllers as well.

**Comment by SativaPhoenix** [comment]
Dear team, will I be able to use this with the Nacon wired pro controller? :D it's not the revolution one;'

**Comment by Ryochan7** [comment]
Probably not. The VID and PID combination of that controller is likely different so DS4Windows would not detect it. Since it seems like a standard DS4 otherwise, I would assume that just including the VID and PID in the lookup list would be enough to add support for that controller.

**Pull request merged**
