### PR TITLE
Translations: DS4Windows updater

### PR DESCRIPTION
**Pull request by RedDevilus**
Update the value to more correct english.

Old window:
image

### CODE REVIEW

**Comment by Masamune3210** [comment]
Imo the hyphens are unneeded, weather the text is treated as on phrase or not the point is still gotten across

**Comment by RedDevilus** [comment]
True, it's a nitpick thing.

**Comment by mika-n** [comment]
Very disturbing when I'm not up-to-date, happened too many times lately. 
Maybe it should be "DS4Windows application is up-to-date"?

**Comment by RedDevilus** [comment]
Done, yeah this looks cleaner overall.

**Comment by hugo2507** [comment]
je ne comprend pas comment telecharger les bon fichier et ouvrir celui qui me permer de jouer avec ma manette de PS5 si quelquun peux maider je suis sous window10 ordi rog strix g15

**Pull request merged**
