### PR TITLE
Port to .NET 5

### PR DESCRIPTION
**Pull request by sitiom**
Saw #1036 and tried to port it to .NET 5. Everything seems to be working well.

Updated the updater to .NET 5 as well
https://github.com/Ryochan7/DS4Updater/pull/1

### CODE REVIEW

**Comment by Ryochan7** [comment]
I'm sorry but I am going to have to reject this pull request for now. .NET 5 is too new and would cause initial breakage for people running Windows 7 still; I am kind of surprised that .NET 5 even supports Windows 7 at all. The plan is to continue targeting .NET Framework for the time being. I guess future projects can possibly target .NET 5 instead.

**Comment by Ryochan7** [comment]
I have been thinking about this again. Especially with Microsoft's new driver policies that now pretty much kills support for anything but Windows 10, there is far less of a need to continue to hold back updates to support older versions of Windows. I would consider having DS4Windows migrate to .NET 5 to ensure future support once Microsoft might start discontinuing support for the .NET Framework.

The tentative plan is to consider a migration to .NET 5 at the end of 2021. I don't remember there being a problem occurring the one time I ran your .NET 5 branch but some more testing would have to be done regarding the third party libraries. Maybe another test branch will be needed for testing but I think this repo is up to 3 active test branches right now. That is a lot of extra work put into changes that aren't usable by the general user base.

**Comment by Ryochan7** [comment]
I would reopen this pull request if it were possible. The task has been added to the Work Board so hopefully I won't forget to look into it.

**Comment by sitiom** [comment]
Ok. Perhaps I should reopen this as a draft pr for tracking.

**Pull request closed without merging**
